### ISSUE TITLE
[Task] Change state metadata payload to `(uint16)ByteArray`

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#1003]
## Description
Change the state metadata payload type to `(uint16)ByteArray`.

## Motivation
The encoded payload section, described in [Anatomy of the State Metadata](https://wiki.iota.org/identity.rs/develop/specs/did/iota_did_method_spec#anatomy-of-the-state-metadata), currently uses a dynamically sized byte array with no specified size (read until end). 

This is problematic because we deviate from the data types in [TIP-21](https://github.com/Wollac/protocol-rfcs/blob/serialization/tips/TIP-0021/tip-0021.md), which only defines fixed-size byte arrays and dynamically sized with a prefixed length. This potentially reduces interoperability and means nothing can be placed after the DID payload in the state metadata field.

## Resources
- [TIP-21](https://github.com/Wollac/protocol-rfcs/blob/serialization/tips/TIP-0021/tip-0021.md)

## Tasks

- Update state metadata packing code.
- Update wiki IOTA DID Method specification.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
