### ISSUE TITLE
[Task] Consider only compile-checking the Wasm Readme rather than executing

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#1009]
## Description

Consider changing the Wasm Readme example to lint only rather than execution with `txm`.

## Motivation

The `npm run test:readme` currently executes the example in the Readme. For the UTXO-based DID method, funds are required to execute the example which means code to request funds from faucet needs to be included in order for the example to run automatically (in CI). Including a lot of irrelevant code in an example in a Readme is undesirable, so an alternative is to generate an address and ask users interactively to request funds on the faucet website. However, that doesn't run in CI because of the manual step.
An alternative then is to not execute the Readme example but only lint it or "compile-check" it. 

The Readme examples are supposed to show the simplicity of creating an identity but requiring a manual step takes away from that. Depending on whether our `Account` replacement for the UTXO method includes functionality to request funds from a faucet, we can consider changing the example to lint only, if it doesn't, or use the automatic faucet request if we do.

## Resources

A Wasm example that requires users to manually requests funds from a faucet.

```typescript
import {
    KeyPair,
    KeyType,
    MethodScope,
    IotaDocument,
    IotaIdentityClient,
    IotaVerificationMethod
} from '../../node';
import { Bech32Helper, IAliasOutput } from '@iota/iota.js';
import { Bip39 } from "@iota/crypto.js";
import * as  readline from "node:readline";
import * as util from 'node:util';
import { Client, MnemonicSecretManager } from "@cycraig/iota-client-wasm/node";

const API_ENDPOINT = "https://api.testnet.shimmer.network/";

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

const question = util.promisify(rl.question).bind(rl);

/** Demonstrates how to update a DID document in an existing Alias Output. */
export async function updateIdentity() {
    // Create a new client with the given network endpoint.
    const client = new Client({
        primaryNode: API_ENDPOINT,
        localPow: true,
    });

    const didClient = new IotaIdentityClient(client);

    // Get the Bech32 human-readable part (HRP) of the network.
    const networkHrp = await didClient.getNetworkHrp();

    // Generate a random mnemonic for our wallet.
    const secretManager: MnemonicSecretManager = {
        Mnemonic: Bip39.randomMnemonic()
    };
    const walletAddressBech32 = (await client.generateAddresses(secretManager, {
        accountIndex: 0,
        range: {
            start: 0,
            end: 1,
        },
    }))[0];

    console.log("Your wallet address is: ", walletAddressBech32);
    await question("Please request funds from https://faucet.testnet.shimmer.network/, then press Enter.");

    // Create a new DID document with a placeholder DID.
    // The DID will be derived from the Alias Id of the Alias Output after publishing.
    const document = new IotaDocument(networkHrp);

    // Insert a new Ed25519 verification method in the DID document.
    let keypair = new KeyPair(KeyType.Ed25519);
    let method = new IotaVerificationMethod(document.id(), keypair.type(), keypair.public(), "#key-1");
    document.insertMethod(method, MethodScope.VerificationMethod());

    // Construct an Alias Output containing the DID document, with the wallet address
    // set as both the state controller and governor.
    const address = Bech32Helper.addressFromBech32(walletAddressBech32, networkHrp);
    const aliasOutput: IAliasOutput = await didClient.newDidOutput(address, document);
    console.log("Alias Output:", JSON.stringify(aliasOutput, null, 2));

    // Publish the Alias Output and get the published DID document.
    const published = await didClient.publishDidOutput(secretManager, aliasOutput);
    console.log("Published DID document:", JSON.stringify(published, null, 2));

    rl.close();
}
```

## To-do list
Create a task-specific to-do list. Please link PRs that match the TODO list item behind the item after it has been submitted.

- [ ] Consider the change.
- [ ] If outcome is positive, only check if the example in the Readme compiles rather than executing it.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
