### ISSUE TITLE
[Task] Add `IotaDID.fromAliasId` to the Wasm bindings

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#1025]
## Description

Add `IotaDID.fromAliasId` to the Wasm bindings.

Note that in Rust this extra method is not required because `AliasId` derefs to `&[u8]` which means it can already be conveniently passed to `IotaDID::new`.

## Motivation

Currently the Wasm bindings require an extra tool to decode the hex-encoded alias id which means a dependency on another package.

```
import { Converter } from '@iota/util.js';

const authorityDid: IotaDID = new IotaDID(Converter.hexToBytes(authorityAliasId), networkName);
```

## Resources

n/a

## To-do list
Create a task-specific to-do list. Please link PRs that match the TODO list item behind the item after it has been submitted.

- [ ] Add a `IotaDID.fromAliasId` function that takes a `aliasId: string` and a `networkName: string` and returns an `IotaDID`.
- [ ] Replace usages of `new IotaDID(Converter.hexToBytes(...), networkName);` with the new function.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
