### ISSUE TITLE
[Task] Add credential and presentation examples

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#1060]
## Description

Add examples for creating, signing, verifying and revoking credentials and presentations. These should match the examples from 0.6 in functionality as much as possible.

## Motivation

Example parity with the 0.6 version.

## Resources

- https://github.com/iotaledger/identity.rs/blob/support/v0.6/examples/account/create_vc.rs
- https://github.com/iotaledger/identity.rs/blob/support/v0.6/examples/account/create_vp.rs
- https://github.com/iotaledger/identity.rs/blob/support/v0.6/examples/account/revoke_vc.rs

## To-do list
Create a task-specific to-do list. Please link PRs that match the TODO list item behind the item after it has been submitted.

- [ ] Port the examples listed in _Resources_ for Rust and Wasm.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by abdulmth** [comment]
Wasm examples still missing
