### ISSUE TITLE
Add Merkle Tree Verification Method

### ISSUE THREAD

**Issue by l1h3r** [iotaledger/identity.rs#110]
Provide a method for representing large quantities of cryptographic keys inside a DID Document.

#### TODO

- [ ] [Spec](https://github.com/iotaledger/identity.rs/pull/112)
- [x] [Merkle Tree Utility](https://github.com/iotaledger/identity.rs/pull/111)
- [ ] Sign/Verify with DID Document
  - [x] [Part 1](https://github.com/iotaledger/identity.rs/pull/109)
  - [ ] [Part 2](https://github.com/iotaledger/identity.rs/pull/112)
