### ISSUE TITLE
[Task] `KeyIdStorage` trait 

### ISSUE THREAD

**Issue by olivereanderson** [iotaledger/identity.rs#1126]
## Description
We need an `IdentityStorage` trait to enable custom plug-ins for storing `KeyId`s generated by a `KeyStorage` (ongoing work in [the storage branch](https://github.com/iotaledger/identity.rs/blob/feat/storage)).

The trait might look something like this: 

```
async trait IdentityStorage {

   /// Insert a [`KeyId`] into the [`IdentityStorage`] under the given `key`. If there already exists an 
   /// entry for `key` in the storage an error must be returned immediately without altering the state 
   /// of the storage. 
   async fn insert_key_id(&self, key: MethodDigest, value: KeyId) -> IdentityStorageResult<()>;

   /// Obtain the `KeyId` associated with the given `key`. 
   async fn get_key_id(&self, key: &MethodDigest) -> IdentityStorageResult<KeyId>;

   /// Delete the `KeyId` associated with the given `key` from the [`IdentityStorage`].   
   async fn delete_key_id(&self, key: &MethodDigest) -> IdentityStorageResult<()>;  
}
``` 

The `MethodDigest` will be a new type uniquely describing key material present in a verification method. There should be a method on `VerificationMethod` returning its `MethodDigest`. Internally `MethodDigest` might look something like this: 
```
pub struct MethodDigest {
    version: u8, 
    value: u64
}

impl AsRef<[u8]> for MethodDigest {
  ...
} 
```
For now the value may be `Hash(<VerificationMethod fragment> + <VerificationMethod.jwk_thumbprint()>)` where `Hash` could be [Seahash](https://docs.rs/seahash/4.1.0/seahash/) (since hash collisions are detected at insertion time a cryptographic hash function is not necessary provided that applications properly guard how methods are inserted into document instances).  If we want to change the properties of `MethodDigest` in the future the `version` field can be made public and one should be able to set which version one wants to work with in the `Storage`. 

 
## Motivation
Higher level methods on the document types will call into `KeyStorage` when creating new verification methods which will then produce a key which can be looked up with the corresponding `KeyId`. We also want to provide a method to sign with the key corresponding to a public key present in a verification method in the given document. For this we need a way to map a verification method to the `KeyId` used by the `KeyStorage`. The `IdentityStorage` trait enables us to persist this mapping.   

## Resources
Sub-task of #1103. 

## To-do list
Create a task-specific to-do list. Please link PRs that match the TODO list item behind the item after it has been submitted.

- [x] Desing an `IdentityStorageError` type ideally inspired by [KeyStorageError](https://github.com/iotaledger/identity.rs/blob/feat/storage/identity_storage/src/key_storage/key_storage_error.rs).   
- [x] Create a `MethodDigest` type. 
- [x] Create the `IdentityStorage` trait described in the issue description. 
- [x] Create an `IdentityStorageMemStore` implementing `IdentityStorage` that we can use in tests. 
- [ ] Create an `IdentityStorage` interface in the bindings, make it callable from Rust and implement `IdentityStorage` for the exported type (see how we did it for the old Storage interface used by the Account). 

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
