### ISSUE TITLE
[Task] Implement SD-JWT 

### ISSUE THREAD

**Issue by eike-hass** [iotaledger/identity.rs#1270]
## Description
Implement the SD-JWT format as an option for issuing and verifying credentials.

## Motivation
Allow the privacy preserving exchange of information following a well defined and established specification.

## Resources
https://datatracker.ietf.org/doc/draft-ietf-oauth-selective-disclosure-jwt/
https://github.com/iotaledger/sd-jwt-payload

## To-do list
Create a task-specific to-do list. Please link PRs that match the TODO list item behind the item after it has been submitted.

- [ ] Rust implementation
- [ ] Wasm implementation

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
