### ISSUE TITLE
[Task] Implement Bitstring Status List

### ISSUE THREAD

**Issue by eike-hass** [iotaledger/identity.rs#1271]
## Description
Implement Bitstring Status List according to the v1.0 specification in a manner that is agnostic regarding the hosting of the Status List credential. 

## Motivation
Allow numbers of revocations that exceed the capabilities of our [current method](https://wiki.iota.org/identity.rs/references/specifications/revocation-bitmap-2022/) and follow a well established method.

## Resources
https://www.w3.org/TR/vc-bitstring-status-list/

## To-do list
Create a task-specific to-do list. Please link PRs that match the TODO list item behind the item after it has been submitted.

- [ ] Rust implementation
- [ ] Wasm implementation

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by eike-hass** [comment]
Blcoked by #1275
