### ISSUE TITLE
[Task] Implement experimental gRPC binding

### ISSUE THREAD

**Issue by eike-hass** [iotaledger/identity.rs#1272]
## Description
Implement an experimental gRPC service to consume selected functions from the library. 

## Motivation
Allow arbitrary host languages to consume the library through a gRPC interface.

## Resources
Link to any resources relevant for the task such as issues, PRs, reference implementations, or specifications.

## To-do list
Create a task-specific to-do list. Please link PRs that match the TODO list item behind the item after it has been submitted.

- [ ] ...

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this. 

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/identity.rs/issues/1323
- [ ] https://github.com/iotaledger/identity.rs/issues/1328
- [ ] https://github.com/iotaledger/identity.rs/issues/1329
- [ ] https://github.com/iotaledger/identity.rs/issues/1330
- [ ] https://github.com/iotaledger/identity.rs/issues/1331
- [ ] https://github.com/iotaledger/identity.rs/issues/1335
```
