### ISSUE TITLE
[Task] Adapt library to IOTA 2.0 / Nova

### ISSUE THREAD

**Issue by eike-hass** [iotaledger/identity.rs#1276]
## Description
Adapt the `did:iota` method to the upcoming version of the IOTA protocol.

## Motivation
Provide a capable DID method taking advantage the unique capabilities of the next version of the IOTA protocol. 

## Resources
https://wiki.iota.org/identity.rs/references/specifications/iota-did-method-spec/
https://github.com/iotaledger/tips (might have to dig through the branches for the 2.0 tips)

## To-do list
Create a task-specific to-do list. Please link PRs that match the TODO list item behind the item after it has been submitted.

- [ ] Research the design and capabilities of IOTA 2.0 and Nova
- [ ] Analyse the current method specification and adapt the CRUD operations to Nova
- [ ] Updated version of method specification (can be used as a design document)
- [ ] Rust implementation
- [ ] Wasm implementation
- [ ] Update wiki content

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this. 

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/identity.rs/issues/1293
```
