### ISSUE TITLE
Create IOTA 2.0 Design Document

### ISSUE THREAD

**Issue by eike-hass** [iotaledger/identity.rs#1293]
```[tasklist]
### Tasks
- [x] Migration Instructions
- [x] New Metadata structure
- [x] Mention Mana
- [ ] Explain Access/Control - MultiAdress, 1-of-n (Multiple Controllers), , k-of-n (MultiSig), Backup Key / Multifactor
- [x] Short "Main differences to previous version" section
- [ ] Consider concurrent access through Multi-Controller
```
