### ISSUE TITLE
[Task] Create Universal Resolver 

### ISSUE THREAD

**Issue by eike-hass** [iotaledger/identity.rs#1312]
## Description
Create a dockerized DIF universal resolver compliant resolver for the IOTA DID method.

## Motivation
Allow an interoperable and standardized way to resolve IOTA DIDs.

## Resources
Link to any resources relevant for the task such as issues, PRs, reference implementations, or specifications.
- https://github.com/decentralized-identity/universal-resolver
- https://github.com/decentralized-identity/universal-resolver/blob/main/docs/driver-development.md

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this. 

```[tasklist]
### Tasks
- [ ] Consider implementation in this or an own repository
- [ ] Consider multi network resolution
- [ ] Figure out Node access
- [ ] Publish to Dockerhub
- [ ] PR to Universal Resolver repo
- [ ] Create DID on mainnet
```
