### ISSUE TITLE
Account API

### ISSUE THREAD

**Issue by l1h3r** [iotaledger/identity.rs#140]
Add an API for managing Identity-related data

### TODO

- [x] Add an optional background-sync process
- [x] Add automatic auth-chain publishing
  - [ ] Ability to change publish threshold
  - [x] Ability to publish with/without key change

**Comment by JelleMillenaar** [comment]
@HenriqueNogara Can you check the state of the above mentioned features and if they exist or not? 

To further clarify them:
> Add an optional background-sync process

If an identity is updated on another device / program, the account should be able to update its internal DID Document to the latest by querying the Tangle (Resolving the Identity) for the latest state and comparing it to its own state. If it is behind, update the internal state. @cycraig and I also recently discussed this, so perhaps he can also provide some thoughts on this topic. 

>  Add automatic auth-chain publishing

Right now, we have integration chain (previously called auth chain) and diff chain messages that a developer could use, but they have too chose themselves. The account should start to make these decisions for the developer instead. Putting new updates in diff messages, unless the diff chain has become to long (variable that the developer can set, lets default to 100). 

>  Ability to change publish threshold

Thats the variable I just mentioned ;D

> Ability to publish with/without key change

It is illegal to change the signing key within a diff chain. If the developer tries to do this, the account should automatically make it a integration chain update.
