### ISSUE TITLE
[Task] Resolve TODOs in the rebased alpha

### ISSUE THREAD

**Issue by itsyaasir** [iotaledger/identity.rs#1437]
## Description
There are couple of outstanding TODOs from the rebased codebase.

## To-do list

- [x] [add entries when identity_iota package is published to well-known networks.](https://github.com/iotaledger/identity.rs/blob/b93128b9f141d424ef4ad3e5996a17cf3ac21ce9/identity_iota_core/src/rebased/client/read_only.rs#L224)
- [x] [remove argument `package_id` and use `EventFilter::MoveEventField` to find the beacon event and thus the package id.](https://github.com/iotaledger/identity.rs/blob/b93128b9f141d424ef4ad3e5996a17cf3ac21ce9/identity_iota_core/src/rebased/client/read_only.rs#L235)
- [x] [authenticate the beacon event with though sender's ID.](https://github.com/iotaledger/identity.rs/blob/b93128b9f141d424ef4ad3e5996a17cf3ac21ce9/identity_iota_core/src/rebased/client/read_only.rs#L237-L238)
