### ISSUE TITLE
Add Selective Disclosure Support to VC

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#144]
As an option, update the way verifiable credentials are signed by hashing individual data points inside the credentialSubject object of a verifiable credential using the Merkle Tree algorithm. The last remaining hash is used to sign the verifiable credential. During the revealing of the verifiable credential, fields may either be revealed or may be replaced by its hash. 

- [ ] Add option to sign using the Merkle Tree, enabling Selective Disclosure for the Holder
- [ ] Salt the individual fields to prevent brute force guessing
- [ ] Generate Verifiable Presentation while hiding/revealing specific fields in the VC
- [ ] Verify a Verifiable Presentation that is signed with the Selective Disclosure method

For reference: [W3C Verifiable Credentials Selective Disclosure](https://www.w3.org/TR/vc-imp-guide/#selective-disclosure)
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/identity.rs/issues/1324
- [ ] https://github.com/iotaledger/identity.rs/issues/1325
```

**Comment by JelleMillenaar** [comment]
This issue needs to be reconsidered with our advanced on ZKP. Does the provided ZKP selective disclosure solution provide full benefits over our Merkle Tree algorithm, or does this have advantages over ZKP making it worth implementing?

**Comment by eike-hass** [comment]
The implementation is shifting towards BBS+ based signatures via [JWPs](https://www.ietf.org/archive/id/draft-jmiller-jose-json-web-proof-00.html)
