### ISSUE TITLE
Add library support for `ControllerCap`, `DelegationToken` and related operations

### ISSUE THREAD

**Issue by UMR1352** [iotaledger/identity.rs#1440]
## Description
Enhance the operations users can perform though our library with regards to `ControllerCap` and `DelegationToken` related operations

## Motivation
Simplifying Identity's AC related operation without having user resort to making _Move_ calls themselves.

## To-do list
- [ ] Handling of `DelegationToken`
- [ ] Code a way to reason about `ControllerCap` and `DelegationToken` generically (enum?)
- [ ] Update APIs that add controllers to also require a `can_delegate` parameter
- [ ] Revocation and unrevocation of `DelegationToken`
