### ISSUE TITLE
Update faucet handling for tests

### ISSUE THREAD

**Issue by wulfraem** [iotaledger/identity.rs#1469]
## Description
Allow using a funded account to distribute funds to test account instead of calling the faucet directly with every test account.

## Motivation
Current implementation makes too many calls against the faucet, which can lead to getting put on an IP based denylist. To reduce those calls, we want to allow using a single funded account and transferring funds to test accounts created during tests.

## To-do list

- [ ] add logic to funds test accounts via a single account
- [ ] behavior must be togglable via env
- [ ] tests must still run; consider adding a mutix, if we run into transaction issues during parallel tests

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
