### ISSUE TITLE
Make sure, that `get_coin_for_transaction` returns a coin object with enoug balance

### ISSUE THREAD

**Issue by wulfraem** [iotaledger/identity.rs#1470]
## Description
When the function `get_coin_for_transaction` retrieves a `Coin` object, we have to make sure, that this coin has a balance big enough, that we can actually use it.

## Motivation
Getting a `Coin` object with low balance might lead to our transaction failing. Even worse, if we get the same `Coint` object for every `get_coin_for_transaction` call, this would lock out the current user from making writing operations to the chain. Also the current implementation is not paging through results, which should be changed.

## To-do list
Add more if points are missing

- [ ] use paging when fetching coins
- [ ] add checks for a minimum balance (value TBD)
- [ ] add tests

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
