### ISSUE TITLE
Add identity::prelude

### ISSUE THREAD

**Issue by l1h3r** [iotaledger/identity.rs#165]
## Description

Define a prelude of commonly used types for the `identity` crate

## Motivation

This is idiomatic rust and makes it easier to work with the library

A good starting point might be:

```rust
pub mod prelude {
  pub use identity::core::KeyPair;
  pub use identity::iota::DID;
  pub use identity::iota::Document;
}
```

which enables to most basic usage:

```rust
use identity::prelude::*;

let keypair = KeyPair::new_ed25519()?;
let document = Document::from_keypair(&keypair)?;
```

## Resources

`std`: https://doc.rust-lang.org/std/prelude/index.html

`rand`: https://docs.rs/rand/0.8.3/rand/prelude/index.html

## To-do list

- [x] Add a `prelude` module to re-export common types

## Change checklist

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by marcianos** [comment]
I have created a prelude locally with the following minimal content:
use identity::crypto::KeyPair;
use identity::iota::Client;
use identity::iota::Document;
use identity::iota::Result;

Examples:
I removed the corresponding imports and replaced them with:
use identity::prelude::*

**Comment by l1h3r** [comment]
Closed by https://github.com/iotaledger/identity.rs/pull/168
