### ISSUE TITLE
Combine Credential and VerifiableCredential types

### ISSUE THREAD

**Issue by l1h3r** [iotaledger/identity.rs#167]
## Description

Combine the `Credential` and `VerifiableCredential` types. We only need to have `VerifiableCredential`.

The same should be done for presentations

## Motivation

The current approach is tedious to work with and doesn't provide any security benefits.

You currently have to wrap a `Credential` with a `VerifiableCredential` to make it signable...

```rust
let mut target = VerifiableCredential::new(credential, Vec::new());
document.sign_data(&mut credential, secret)?;
```

...instead, you should be able to sign a `Credential` directly:

```rust
document.sign_data(&mut credential, secret)?;
```

## To-do list

- [ ] Merge `VerifiableCredential` -> `Credential`
  - [ ] `proof`/`proof_mut` methods
  - [ ] `identity_core::crypto` trait implementations
  - [ ] Change `proof` type: `OneOrMany<Signature>` -> `Option<Signature>`

- [ ] Merge `VerifiablePresentation` -> `Presentation`
  - [ ] `proof`/`proof_mut` methods
  - [ ] `identity_core::crypto` trait implementations
  - [ ] Change `proof` type: `OneOrMany<Signature>` -> `Option<Signature>`

## Change checklist

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by JelleMillenaar** [comment]
In some cases you may want to send a non-signed verifiable credential in order to get it signed by an Issuer. We need to make sure that the workflow for that is still possible with this change.

**Comment by DeppLearning** [comment]
> In some cases you may want to send a non-signed verifiable credential in order to get it signed by an Issuer. We need to make sure that the workflow for that is still possible with this change.
- Conceptually, does it make sense to sign a verifiable credential more than once?
- Is this true about presentations and verifiable credentials?
- @l1h3r if we still need to make a distinction, this sounds like it could be modeled with a state-machine:

```mermaid
graph TD
    C[Credential] -->|sign| VC(Verifiable Credential)
    VC -->|sign| VC
```

**Comment by DeppLearning** [comment]
> OneOrMany<Signature> -> Option<Signature>
 
Was this intended? That would deviate from specs wouldn't it?

I came across another issue:

The `Credential` struct has no `proof` field, while the `VerifiableCredential` has one. If I move this field to `Credential`, that creates an issue when parsing a `Credential` from the test fixtures Jsons. Those fixtures have `proof` fields, sometimes valid ones, sometimes only the `type` field is populated (invalid?).

If `Credential` gains the `proof` field, the `proof` field on those fixtures will be attempted to be deserialzed, which fails in cases of those "invalid" ones (i.e. identity-credential/tests/fixtures/credential-1.json). Can we just adjust the fixtures or does that point to a deeper problem?

**Comment by l1h3r** [comment]
> Was this intended? That would deviate from specs and not allow for multiple proofs anymore, wouldn't it?

Intended yes, technically can be one or more:

> At least one proof mechanism, and the details necessary to evaluate that proof, MUST be expressed for a credential or presentation to be a verifiable credential or verifiable presentation; that is, to be verifiable.

I wouldn't say this change deviates from the standard. Multiple proofs were never actually supported to begin with (just used `get(0)` on `OneOrMany`); it would be better to add that as a new feature if it was ever needed

**Comment by l1h3r** [comment]
> Can we just adjust the fixtures or does that point to a deeper problem?

90% of those fixtures look like they have invalid proofs anyways (I believe I copied these straight from the standard though)

only `credential-5.json` looks like it's valid (and we don't even support `RsaSignature2018` right now)
