### ISSUE TITLE
[Enchancement] Add Test coverage 

### ISSUE THREAD

**Issue by Druelik** [iotaledger/identity.rs#169]
## Description
Adding source-based code coverage 
## Motivation
There should be better testing.

## Resources

[crypto.rs](https://github.com/iotaledger/crypto.rs/pull/68) (we should copy this - in-house tool)

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [x] Add Coverage Badge
- [x] Add Github workflow for testing
- [x] Make project wide testing guidelines

**Comment by Druelik** [comment]
will be closed by #177

**Comment by Druelik** [comment]
closed by #177
