### ISSUE TITLE
Improve identity::iota::Document type consistency

### ISSUE THREAD

**Issue by l1h3r** [iotaledger/identity.rs#172]
## Description

The `Deref` implementation for `identity::iota::Document` leads to situations where unexpected "core" types are returned when IOTA-specific types are expected.

This trait can be removed and the relevant methods from `iota::did::Document` can be re-implement in `identity::iota::Document` while also performing the necessary type conversions.

## Motivation

This can be confusing and often leads to type inconsistencies

## Resources

https://rust-unofficial.github.io/patterns/anti_patterns/deref.html

> There is no one good alternative

## To-do list

- [x] Remove `Deref` from `identity::iota::Document`
- [x] Validate all DID Document verification methods in `iota::Document::try_from_core`**
  ```rust
  for method in document.methods() { Method::check_validity(method)?; }
  ```

- [x] Re-implement the following methods for `identity::iota::Document`***:
  - [ ] controller
  - [ ] methods
  - [ ] resolve
  - [ ] try_resolve

** This is required for `unsafe` casts between references (safe alternatives require a clone and refs are needed for iterators, etc.)

*** This should just call the "core" document method and convert the output type (see `iota::Document::id(...)`)

## Change checklist

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by m-renaud** [comment]
I can pick this one up.

**Comment by m-renaud** [comment]
The following also need to be re-implemented:

- `proof()`
- `verifier()`
- `signer()`
- `service()`

Additionally, removing the `Deref` impl didn't actually cause any failures due to missing `controller()`, `methods()`, `resolve()`, or `try_resolve()` calls. So, I think I'll start with a PR to expand test coverage, and then send a follow-up to remove the `Deref` impl.

**Comment by m-renaud** [comment]
Hmm, ran into another issue: `impl From<BaseDocument> for IotaDocument`

This appears to be "unsafe" since there is no validation that the underlying `BaseDocument` (ie. `CoreDocument<Properties, Object, Object>` actually coforms to the IOTA DID spec.

I think this should be replaced with a `TryFrom<BaseDocument>` impl and the `From<BaseDocument> instance deleted.

Do you agree @l1h3r ? Or is there something I'm missing/misunderstanding?

**Comment by m-renaud** [comment]
One more question: both `IotaDocument::resolve_mut()` and `IotaDocument::try_resolve_mut()` return mutable (obviously) references to the underlying `VerificationMethod`s, which means at any point these could be modified to no longer conform to the IOTA spec.

Soooo not sure exactly what we want to do here, maybe outside the scope of fixing the "safe" unsafe functions.

**Comment by l1h3r** [comment]
> I think this should be replaced with a `TryFrom<BaseDocument>` impl and the `From instance deleted.

Yes! This conversion needs to be fallible (you should be able to re-use the validation from `try_from_core`)

`resolve_mut` is out-of-scope since it was never available through `Deref`. `try_resolve_mut` is actually already re-implemented but with `#[doc(hidden)]` - should be able to add both **after** adding validation for all verificaton method (separate issue/PR is probably best)

**Comment by m-renaud** [comment]
I think this was resolved in the above linked PR. Can we close this out? I separately have a PR for removing the Deref anti-pattern in `IotaDID`.

**Comment by l1h3r** [comment]
Closed by https://github.com/iotaledger/identity.rs/pull/233 and https://github.com/iotaledger/identity.rs/pull/269
