### ISSUE TITLE
[Task] Rename Authentication Key and Chain

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#195]
## Description
Describe the task, this may be scoped beyond a single PR.

Instead of using the authentication field and key for DID messages, utilize a general verification method. As this removes the logic behind the authentication chain name, I request a rename to the Integration chain (Also in the code). The name of the key we use for signing DID messages may be anything, but we can default to #_sign-x, where x is the number of the key, incremented every time it is updated. This should not be enforced though. 

## Motivation
Describe the motivation for the feature to be developed.

We currently always use an authentication key for signing and updating DID messages. This doesn't fall in line with the standardized way of using the authentication verifiable relationship according to the DID standard. Instead, we should utilize a general verification method.

## Resources
Link to any resources relevant for the task such as Issues, PRs, reference implementations, or specifications.

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [x] Rename AuthChain and other references to IntChain (Integration Chain) in the code
- [ ] Remove enforcement of signing with "auth key"
- [ ] Edit examples to add verification method with a #_sign-1 key.
- [ ] Edit account to standardize the #_sign-x naming instead of auth keys.
- [x] Edit documentation to rename all references to AuthChain

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by JelleMillenaar** [comment]
@PhilippGackstatter I believe most of this is done, but I am unsure if we removed the enforcement of "auth keys" and the naming. Can you check and close if it is all done?
