### ISSUE TITLE
Fix MessageIndex determinism

### ISSUE THREAD

**Issue by l1h3r** [iotaledger/identity.rs#201]
## Description

values stored in `MessageIndex` should be ordered by `message_id`, currently they are not

## Motivation

required for resolution

## To-do list

- [x] Ensure values added to `MessageIndex` are sorted by `T::message_id`
  - [x] Replace `scope.insert` with equivalent binary search

## Change checklist

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by DeppLearning** [comment]
> values stored in `MessageIndex` should be ordered by `message_id`, currently they are not
> ## To-do list
>       * [ ]  Replace `scope.insert` with equivalent binary search

I'm confused where you want the messages ordered. This is the current impl:

https://github.com/iotaledger/identity.rs/blob/97cfa59a334aac58ba3fb67e3061e01e1b6938f4/identity-iota/src/tangle/message_index.rs#L13-L18

The `scope` you are referring to is the inner Vec<T>, ordering by message_id should hardly make any sense here (since all values in that vector should correspond to the same message_id)?

When changing the HashMap to BTreeMap 
> values stored in MessageIndex should be ordered by message_id

so that's what I did in #213

**Comment by l1h3r** [comment]
> The scope you are referring to is the inner Vec, ordering by message_id should hardly make any sense here (since all values in that vector should correspond to the same message_id)?

The key for the map is `previous_message_id` and `message_id` is expected to be unique for all values (`T` has `message_id` and `previous_message_id` methods through the `TangleRef` trait).

Something like this:

```
map(previous_message_id => [(message_id, data), ...])
```

If there are multiple messages with the same `previous_message_id` they will just be prepended here:

https://github.com/iotaledger/identity.rs/blob/37d3996ba2ea4874f65b923a9244fa15c26acc56/identity-iota/src/tangle/message_index.rs#L51

and this is where ordering by `message_id` should happen
