### ISSUE TITLE
[Task] Equalize examples between Rust and WASM

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#221]
## Description
Describe the task, this may be scoped beyond a single PR.

Rewrite the examples for the WASM bindings to match the examples of Rust. 

## Motivation
Describe the motivation for the feature to be developed.

Javascript developers need better examples to understand the repository. We expect large adoption from that specific language, so the examples need to be of high quality. 

## Resources
Link to any resources relevant for the task such as Issues, PRs, reference implementations, or specifications.

* [Rust examples](https://github.com/iotaledger/identity.rs/tree/dev/examples)

## To-do list
Create a task-specific to-do list. Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Write examples readme, reusing the table if possible. 
- [ ] Port all examples to WASM node.js environment
- [ ] Port all examples to WASM web environment (Reuse as much code as possible)

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
