### ISSUE TITLE
[Task] Rename JSON serialization field names to use camelCase

### ISSUE THREAD

**Issue by m-renaud** [iotaledger/identity.rs#222]
## Description

Re-name non-camelCase JSON field names to use camelCase to conform to the JSON spec.

## Motivation

This came up in #207 when it was noted that the `previous_message_id` field used snake case instead of camelCase. @JelleMillenaar suggested to file an issue to track this.

This also means that the IOTA implementation does not match the spec.

## Resources

This can be accomplished via the serde `rename` attribute.

**Example:**

```rust
// Before:
#[serde(rename = "previous_message_id")]

// After:
#[serde(rename = "previousMessageId")]
```

## To-do list

- [ ] Rename `did-url-dereferencing-metadata` -> `dereferencingMetadata` (`identity-did/src/resolution/dereference.rs`)
- [ ] Rename `content-stream` -> `contentStream` (`identity-did/src/resolution/dereference.rs`)
- [ ] Rename `content-metadata` -> `contentMetadata` (`identity-did/src/resolution/dereference.rs`)
- [ ] Rename `invalid-did` -> `invalidDid` (`identity-did/src/resolution/error_kind.rs`)
- [ ] Rename `not-supported` -> `representationNotSupported` (`identity-did/src/resolution/error_kind.rs`)
- [ ] Rename `not-found` -> `notFound` (`identity-did/src/resolution/error_kind.rs`)
- [ ] Rename `did-resolution-metadata` -> `didResolutionMetadata` (`identity-did/src/resolution/resolution.rs`)
- [ ] Rename `did-document` -> `didDocument` (`identity-did/src/resolution/resolution.rs`)
- [ ] Rename `did-document-metadata` -> `didDocumentMetadata` (`identity-did/src/resolution/resolution.rs`)
- [ ] Rename `previous_message_id` -> `previousMessageId` (`identity-iota/src/did/doc/diff.rs`)

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by m-renaud** [comment]
I should be able to get a PR out this week for this.

**Comment by l1h3r** [comment]
you can also probably use `#[serde(rename_all = "camelCase")]`

**Comment by l1h3r** [comment]
`did-url-dereferencing-metadata` <- this is actually the naming convention used for the targeted version of [did-core](https://www.w3.org/TR/2020/WD-did-core-20200731/#resolution), might make sense to hold off on renaming those ones until we move to a later version of the spec? @JelleMillenaar?

**Comment by m-renaud** [comment]
> `did-url-dereferencing-metadata` <- this is actually the naming convention used for the targeted version of [did-core](https://www.w3.org/TR/2020/WD-did-core-20200731/#resolution), might make sense to hold off on renaming those ones until we move to a later version of the spec? @JelleMillenaar?

Ahh I wasn't aware the current impl targetted an older version, I was looking at https://www.w3.org/TR/did-core/#did-url-dereferencing. I'm assuming this is related to #196, will await @JelleMillenaar's response. If we do want to hold off, is the one you quoted the only one that we should wait for, or are there others?

I looked at the page you linked and wasn't able to find `did-url-dereferencing-metadata` (or similar) anywhere in the text, was the exact name never specified?

**Comment by l1h3r** [comment]
Yeah, hopefully we will move to a newer version soon - it will likely be a focus after the initial account module is released.

> I looked at the page you linked and wasn't able to find did-url-dereferencing-metadata (or similar) anywhere in the text, was the exact name never specified?

This is from a separate did resolution document that further explains the process: https://w3c-ccg.github.io/did-resolution/

It's also not versioned (and now 10x more informative than when I initially read it)

**Comment by m-renaud** [comment]
> This is from a separate did resolution document that further explains the process: https://w3c-ccg.github.io/did-resolution/

Ahhh I see, it looks like most of the renames I proposed above correspond to the format in that document.

**Comment by m-renaud** [comment]
Also, I see that @JelleMillenaar 👍'd the issue, which I assume means "go ahead and make these changes", so I'll put together a PR. If my assumption is wrong please let me know 🙃

**Comment by m-renaud** [comment]
> you can also probably use #[serde(rename_all = "camelCase")]

That could work, although being able to explicitly search in the codebase for name the spec defines seems like a benefit of being explicit with `#[serde(rename = "invalidDid")]`.

If you have strong opinions one way or the other lmk 🙂

**Comment by m-renaud** [comment]
Meta: GitHub not having threaded comments on issues (only on "Discussions") is...annoying 😝

**Comment by l1h3r** [comment]
> That could work, although being able to explicitly search in the codebase for name the spec defines seems like a benefit of being explicit with `#[serde(rename = "invalidDid")]`.

Sounds good, let's keep the codebase easier to navigate

**Comment by l1h3r** [comment]
So after chatting with @JelleMillenaar earlier today we are aiming for a release next week with the changes for Chrysalis - at the moment it probably makes sense to just change `previous_message_id` to `previousMessageId` and we'll start updating to the latest DID spec in the coming weeks.

Sound good @m-renaud ?

**Comment by l1h3r** [comment]
> Meta: GitHub not having threaded comments on issues (only on "Discussions") is...annoying 😝

We can convert it to a discussion which also locks and closes the issue

**Comment by JelleMillenaar** [comment]
@m-renaud Was this all done? If so, please close, otherwise could you have another go at it? :)

**Comment by m-renaud** [comment]
IIRC the plan was to wait for #196 to be resolved to update to the new DID spec; not sure if that's been completed or not. In any case I can put together a PR to perform the other renamings.
