### ISSUE TITLE
[Bug] NodeURL should not autocompleted "/api/v1/"

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#279]
## Description
Describe the task, this may be scoped beyond a single PR.

We provide a node URL and the client autocompletes this with `/api/v1/` to do the API calls, but that is not a guaranteed setup.

## Motivation
Describe the motivation for the feature to be developed.

Chronicle and user set up nodes may not have `/api/v1/` in their endpoints. 

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Remove `/api/v1/` from the client
- [ ] Edit default nodes and (WASM) examples to write out nodeURLs to include `/api/v1`
- [ ] Publish NPM dev version for WASM

**Comment by l1h3r** [comment]
I think the issue is in iota.rs (we don't build the endpoints) and is a duplicate of https://github.com/iotaledger/iota.rs/issues/527
