### ISSUE TITLE
[Task] Add clearer Verifiable Presentation examples

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#295]
## Description

The current examples don't clearly show or explain the purpose of Verifiable Presentations. The example should show how Verifiable Presentations are signed by the Holder and how the Verifier may verify this. In addition, a Verifiable Presentation often is signed using either a timestamp or challenge, the example should showcase both. In both cases the content of the Verifiable Presentation must be checked to see if the timestamp is recent or if the challenge nonce has the expected value. Lastly, signing a Verifiable Presentation proves that the holder controls the DID, but a check must be made that the signing DID matches the DID inside the Verifiable Credential(s).

## Motivation

It is currently poorly understand how Verifiable Presentations should be used. 

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Sign timestamp and verify timestamp to be recent (e.g. <3 sec old)
- [ ] Sign with challenge and verify challenge
- [ ] Verify signing DID matches VC DID(s)
- [ ] Implement also in WASM

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by olivereanderson** [comment]
This will be solved in this PR: https://github.com/iotaledger/identity.rs/pull/599 (when it is ready to be reviewed).
