### ISSUE TITLE
[Task] Change DID publicKey formats to "publickeyMultibase" according to DID standard

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#296]
## Description

Implement support for `publickeyMultibase` according to the new DID standard. 

## Motivation

Stay compliant with W3C standard

## Resources

* [W3C](https://www.w3.org/TR/did-core/#dfn-publickeymultibase)

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Research potential crates to use
- [ ] Implement `publickeyMultibase` via crate or ourselves (may limit to subset of useful encodings)
- [ ] Clean up older encoding code such as `publicKeyBase58`

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by l1h3r** [comment]
> The publicKeyMultibase property is OPTIONAL. This feature is non-normative.

I don't really want to rush to make this change. It seems it was added to the standard fairly recently and is still being debated in various GitHub issues over at [did-core](https://github.com/w3c/did-core).

We should still update the version of the DID standard but preferably to a more notable release like the [previous Candidate Recommendation](https://www.w3.org/TR/2021/CR-did-core-20210318/) from March 18.

After updating to this version we could include the `publicKeyJwk` field which is included in the later versions and doesn't appear to be at risk like `publicKeyBase58` was.

Thoughts?

**Comment by cycraig** [comment]
While the `publicKeyMultibase` feature is non-normative it has still supplanted `publicKeyBase58` (which was also non-normative) in the [did-core specification](https://www.w3.org/TR/did-core/), which we use in various places. The main discussion at https://github.com/w3c/did-core/issues/707 seems conclusive in that at least.  The aim in the change seems to be future extensibility for new bases without having to revise the supported `publicKey<base>` values for each one added.

I am of the opinion that we should add support for `publicKeyMultibase`  now, in addition to `publicKeyBase58` for temporary backwards compatibility, and phase out uses of the latter over time until we can remove it with a major release, e.g. 1.0. 
The reason I prefer a phased removal is because the [did-core specification](https://www.w3.org/TR/did-core/) still retains several examples using `publicKeyBase58` (whether intentionally or erroneously) so it is unclear to me if we should still support it in the future. Once their examples have been updated I would be happy to push for removing it from the codebase entirely.

> After updating to this version we could include the `publicKeyJwk` field which is included in the later versions and doesn't appear to be at risk like `publicKeyBase58` was.

Agreed, [`publicKeyJwk`](https://www.w3.org/TR/did-core/#dfn-publickeyjwk) is normative so it takes a higher priority. It also needs its own issue that should be added to the list in #196.

**Comment by cycraig** [comment]
Regarding implementing `publicKeyMultibase`:

The [multibase crate](https://github.com/multiformats/rust-multibase) seems lightweight and supports all the encodings on the [Multibase draft specification](https://datatracker.ietf.org/doc/html/draft-multiformats-multibase-03).

It runs on the `wasm32-unknown-unknown` target and has relatively few dependencies, of which `syn` and `data-encoding` already exist in our dependency tree. 
```
multibase v0.9.1
├── base-x v0.2.8
├── data-encoding v2.3.2
└── data-encoding-macro v0.1.12
    ├── data-encoding v2.3.2
    └── data-encoding-macro-internal v0.1.10 (proc-macro)
        ├── data-encoding v2.3.2
        └── syn v1.0.73 (*)
```

It also shows similar performance to the `bs58` crate currently used for `publicKeyBase58`. Timings from [Criterion ](https://github.com/bheisler/criterion.rs) benchmarks when processing random Ed25519 public keys to/from Base58-Bitcoin:

|   | bs58 | multibase |
| ------------- | ------------- | ------------- |
| encode  | 1247 ns  | 683 ns  |
| decode | 590 ns | 462 ns  |

Given that the crate seems to have low overhead, and that [Multibase specifies 22 encodings](https://datatracker.ietf.org/doc/html/draft-multiformats-multibase-03#appendix-D.1), I am of the opinion that we should simply use it directly rather than implementing Multibase or a subset thereof ourselves.

An alternative crate is [multiformats](https://github.com/bnclabs/multiformats). However, it has unnecessary features (for our case) and dependencies as it implements hashing algorithms and other codecs in addition to Multibase, so it is overall less suited.

Aside: one thing to note is that we cannot support the [identity (0x00) base](https://datatracker.ietf.org/doc/html/draft-multiformats-multibase-03#appendix-D.1) since arbitrary bytes from a key cannot be represented as a UTF-8 string in general. Since `publicKeyMultibase` is specified as a [UTF-16 string](https://infra.spec.whatwg.org/#string), it shouldn't ever be a problem.

**Comment by cycraig** [comment]
Link to PR marking `publicKeyMultibase` as at-risk in the did-core specification: https://github.com/w3c/did-core/pull/772

**Comment by JelleMillenaar** [comment]
@cycraig This can be closed, right?

**Comment by cycraig** [comment]
While the multibase functionality is complete, I believe we still default to `publicKeyBase58` instead of `publicKeyMultibase` in several components and examples, such as verification methods. 

Whether or not to remove `publicKeyBase58` entirely for some/all components is also still up for debate, but several examples in did-core still use it so I'm leaning towards keeping it for backwards compatibility.
