### ISSUE TITLE
[Task] Implement Basic Agent

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#299]
## Description

Implement a basic agent for the IOTA Identity framework for performing operations related to a stronghold, such as key creation and signing. The agent should be able to set up secure communication via the Stronghold P2P Communications crate. Lastly, it should allow developers to overwrite the agent or insert pre and post hooks to the default logic. 

## Motivation

Agents are a common idea in the SSI world. It allows different Identity-enabled entities to identify each other and speak in a common language to build trust and exchange trusted information. In addition, it allows a single entity to out-source its operations to another location (web -> desktop or x -> server), which may be more secure. This way we enable secure identity usage in unsecure environment such as the web. 

## Resources
Link to any resources relevant for the task such as Issues, PRs, reference implementations, or specifications.

- [Hyperledger Agent Javascript](https://github.com/hyperledger/aries-framework-javascript)
- [Hyperledger Agent Python](https://github.com/hyperledger/aries-cloudagent-python)
- [Stronghold Actors](https://github.com/iotaledger/stronghold.rs/tree/dev/client/src/actors)

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Implement agent for stronghold operations
- [ ] Set up secure communications between two agents via P2P
- [ ] Rust <-> WASM agent test
- [ ] Add hooks

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
