### ISSUE TITLE
[Task] Extend Agent with DID Comm Functionalities 

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#300]
## Description

DID Communications is a standard from the Decentralized Identity Foundation (DIF) that enables different entities that utilize SSI, to talk to each other in a common language. They can use this language to establish trust, share trustworthy information and request things from each other. 

The task requires to add DID Comm functionalities to the Identity Agent. This includes all the different interactions researched and specified in the specifications folder. Whether we should implement our own specifications or those from Aries (to maximize interoperability) needs to be investigated.

## Motivation

It provides a way to create out-of-the-box interoperability between different applications using IOTA Identity.

## Resources

- [Our Spec](https://github.com/iotaledger/identity.rs/tree/dev/docs/DID%20Communications%20Research%20and%20Specification)
- [DIF Rendered Draft](https://identity.foundation/didcomm-messaging/spec/)
- [DIF Spec Files (More up-to-date then render)](https://github.com/decentralized-identity/didcomm-messaging/tree/master/docs/spec-files)

## To-do list

Please open a new PR per task for this issue.

- [ ] [Trust Ping](https://github.com/iotaledger/identity.rs/blob/dev/docs/DID%20Communications%20Research%20and%20Specification/i_trust-ping.md)
- [ ] [Feature Discovery](https://github.com/iotaledger/identity.rs/blob/dev/docs/DID%20Communications%20Research%20and%20Specification/i_features-discovery.md)
- [ ] [DID Discovery](https://github.com/iotaledger/identity.rs/blob/dev/docs/DID%20Communications%20Research%20and%20Specification/i_did-discovery.md)
- [ ] [DID Authentication](https://github.com/iotaledger/identity.rs/blob/dev/docs/DID%20Communications%20Research%20and%20Specification/i_authentication.md)
- [ ] [DID Resolution](https://github.com/iotaledger/identity.rs/blob/dev/docs/DID%20Communications%20Research%20and%20Specification/i_did-resolution.md)
- [ ] [Credential Options](https://github.com/iotaledger/identity.rs/blob/dev/docs/DID%20Communications%20Research%20and%20Specification/i_credential-options.md)
- [ ] [Credential Schema](https://github.com/iotaledger/identity.rs/blob/dev/docs/DID%20Communications%20Research%20and%20Specification/i_credential-schema.md)
- [ ] [Credential Issuance](https://github.com/iotaledger/identity.rs/blob/dev/docs/DID%20Communications%20Research%20and%20Specification/i_credential-issuance.md)
- [ ] [Credential Revocation](https://github.com/iotaledger/identity.rs/blob/dev/docs/DID%20Communications%20Research%20and%20Specification/i_credential-revocation.md)
- [ ] [Presentation Verification](https://github.com/iotaledger/identity.rs/blob/dev/docs/DID%20Communications%20Research%20and%20Specification/i_presentation-verification.md)
- [ ] [DID Introduction](https://github.com/iotaledger/identity.rs/blob/dev/docs/DID%20Communications%20Research%20and%20Specification/i_did-introduction.md)

## Change checklist per item

- The feature or fix is implemented in Rust and across all bindings whereas possible.
- The feature or fix has sufficient testing coverage
- All tests and examples build and run locally as expected
- Every piece of code has been document according to the documentation guidelines.
- If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by eike-hass** [comment]
Agent and DIDComm are out of the current scope of the library
