### ISSUE TITLE
[Task] Migrate Documentation Portal to Docusaurus

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#301]
## Description

Migrate the documentation from MdBook to the Docusaurus. 

## Motivation

Nicer looking and more feature rich documentation portal.

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Deploy docusaurus documentation portal
- [ ] Move existing documentation from mdBook (docs folder) to docusaurus
- [ ] Remove mdBook related files

**Comment by abdulmth** [comment]
To do before deployment: 

- [ ] Update the edit links in docusaurus.config.js
- [ ] Remove/update copyright string in docusaurus.config.js
- [ ] Cookies consent?
