### ISSUE TITLE
[Task] Update WASM web examples

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#303]
## Description

Similar to the node.js examples, the web examples need to be split into several examples. These examples must mirror the logic of the node.js examples. 

## Motivation

Provide better support and documentation for the targeted web environment.

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Fix example to work with latest WASM bindings
- [ ] Split into several examples, mirroring node.js functionalities

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
