### ISSUE TITLE
[Task] Implement the Account high-level API in WASM

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#304]
## Description

Implement the high-level API of the account into WASM. This requires WASM bindings to be implemented for the account API and examples to be added to the node and web. This binding may completely exclude the Stronghold integration in Rust as that will be a separate topic / issue. 

## Motivation

Improve the WASM developer experience

## Resources
Link to any resources relevant for the task such as Issues, PRs, reference implementations, or specifications.

- Depends on #291 

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [X] Implement WASM bindings for the account https://github.com/iotaledger/identity.rs/pull/681
- [X] Write matching examples to the Rust account examples for both node.js and web environments. https://github.com/iotaledger/identity.rs/pull/681
- [ ] Configure a project for both the browser and Node.js with proper TypeScript configuration and linting (make sure code completion works, source map ..etc). 
- [X] Add nightly example testing to CI. (Examples will now run in our regular `build-and-test` job) https://github.com/iotaledger/identity.rs/pull/681
- [ ] Migrate the needed low level examples to the new project.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by eike-hass** [comment]
I can take care of running the examples in CI.
