### ISSUE TITLE
[Doc] Add web examples to documentation portal

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#305]
## Description

Add the WASM web examples to the documentation portal on its own category. The examples should show the code to be executed, an execution button and a place to display the result. This entire process should be modularized towards a react component such that the same component can be used for the different examples, also within other places of the documentation portal. 

## Reference material
Links resources such as RFCs, specifications, and other documentation. 

* [Svelte examples](https://svelte.dev/examples#hello-world)
* [Old Documentation Portal](https://legacy.docs.iota.org/docs/client-libraries/1.0/getting-started/js-quickstart#run-the-code)

## To-do List
Create a task-specific to-do list 

- [ ] Create examples category
- [ ] Create browser execution component
- [ ] Implement all WASM examples
