### ISSUE TITLE
[Task] Let VCs and VPs throw errors during validation, include expiration functionalities.

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#312]
## Description

Currently Verifiable Credentials and Verifiable Presentation either return true or false during validation. It would be more clear to add why a validation failed, therefore we should throw an error (code). In addition, a credential doesn't check if it has been expired, this should be added.

## Motivation

Provide user more information on what is wrong. 

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Check for valid expiration and issuance dates
- [ ] Align on error strategy within the framework that is FFI compatible
- [ ] Return error(codes)

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by olivereanderson** [comment]
For more context:
In the case of verifiable credentials this is the boolean field https://github.com/iotaledger/identity.rs/blob/dev/identity-iota/src/credential/validator.rs#L24 that is used to indicate whether the validation was successful or not.  The reason for this field to be present in the type is that there are situations where one may want to permit credentials that are technically invalid (for instance in some countries a recently expired drivers licence may still be considered as valid for identification purposes, even though it no longer permits the owner to drive). On the other hand the return type of https://github.com/iotaledger/identity.rs/blob/dev/identity-iota/src/credential/validator.rs#L78 is ` Result<CredentialValidation<T>>`, indicating that errors are part of the `Err` variant, it is indeed somewhat awkward to have a "verified" field in the CredentialValidation struct.

**Comment by olivereanderson** [comment]
A provisional (currently Rust only) implementation can be found in this draft PR https://github.com/iotaledger/identity.rs/pull/564. It adds a lot more type safety and the ability to specify which deficiencies in the credential are acceptable during validation. It needs some more tests and a little more thought needs to be put into the API.

**Comment by olivereanderson** [comment]
This functionality will be part of this PR: https://github.com/iotaledger/identity.rs/pull/599
