### ISSUE TITLE
[Task] Allow FFIs to interact with Stronghold

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#314]
## Description

Allow FFIs such as the WASM bindings for the node.js environment to interact with Stronghold. The biggest hurdle will be to figure out an architecture were Stronghold will not be required to have FFIs themselves. The actor model should help out with this as it creates a separation between Identity and Stronghold.

## Motivation

Enable Stronghold functionality across all FFIs (In non-web environments). 

## Resources

Depends on #299 and #304 

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [X] Make architectural design for Identity Account <->Stronghold interactions for FFIs https://github.com/iotaledger/identity.rs/pull/681
- [X] Implement for WASM (Nodejs) https://github.com/iotaledger/identity.rs/pull/681
- [ ] Potentially copy architectural set up over to Rust Identity Account <-> Stronghold interactions

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [X] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [X] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
