### ISSUE TITLE
[Tool] Online DID Resolver and Debugger

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#326]
## Description

Implement a web-based tool that provides user with the ability to resolve a DID Document, such that it either displays the latest DID Document or that it provides an entire history of all DID messages associated to the Identity, for debugging purposes. 

The tool should provide a search bar that takes a DID that implements the `iota` DID method. Once it has been entered, the DID Resolver resolves the DID and displays the latest DID Document. A debug option should be toggled where the user may query the entire history of the DID, which means all DID messages are queried and displayed. This entire history includes incorrect DID messages or garbage messages that are posted on the same index. The invalid messages should try to display an error on why they are treated as incorrect DID messages and ignored by the framework. The messages should at least contain the entire Integration Chain messages, but also the latest Diff Chain messages. Older Diff chain messages can be queried on demand. 

## Motivation

* Make it easy to resolve identities on the web and engage with DIDs.
* Provide debug tooling for IOTA Identity developers to find out why an Identity acts unexpectedly. 

## Resources

This solution will be build as part of the [IOTA explorer](https://github.com/iotaledger/explorer). 

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

The following topics can individually be produced and PR'd, providing a gradually improving tool. 
- [ ] Implement basic DID resolver
- [ ] Follow UX designs (once designed by UX-team). 
- [ ] Showcase entire Integration Chain messages and latest Diff Chain messages in Debug mode
- [ ] Scan DID messages and try to determine why some messages fail to be seen as valid DID messages.

**Comment by eike-hass** [comment]
I think the functionality should be accessible via url deeplinking, so we can reference the tool from e.g. error messages or other apps. 
We should also maybe consider integrating a diff view for valid Int- oder Diffchain messages.
