### ISSUE TITLE
[Task] Update Wasm README.md examples

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#342]
## Description
Fix the Wasm README.md examples and test them periodically via GitHub Actions.

## Motivation
The Wasm examples in [wasm/bindings/README.md](https://github.com/iotaledger/identity.rs/blob/4625b47319d478fd3ded024251d4c47816c33e1f/bindings/wasm/README.md) are outdated and no longer compile on the `dev` branch. 

Those examples become outdated quite often, and can take days/weeks to notice, so they should be tested via GitHub Actions to ensure they compile at minimum. They could be added to the existing `build-and-test` pipeline or have a new pipeline that runs periodically on a schedule (much like the `audit` task) if they prove to be brittle/inconsistent.

**Update:**

Tools for running code blocks in markdown files:
- [txm](https://github.com/anko/txm)
- [markdown-doctest](https://github.com/Widdershin/markdown-doctest)
- [byexample](https://byexamples.github.io/byexample/)
- [runmd](https://github.com/broofa/runmd)

Of the above options, I found only [txm](https://github.com/anko/txm) to work out-of-the-box. The rest either threw inscrutable errors or had complex setups that would take too much time to learn personally.

## To-do list

- [x] Investigate markdown tester options
- [x] Update `wasm/bindings/README.md` examples - PR #345 
- [x] Add example tests to GitHub Actions - PR #345 

## Change checklist

- [x] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [x] The feature or fix has sufficient testing coverage
- [x] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
