### ISSUE TITLE
[Task] Add Wasm examples to GitHub Actions

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#343]
## Description
Add runnable examples to the GitHub Actions CI pipeline.

## Motivation
While the Rust examples are strongly-typed and compiled in the `build-and-test` pipeline, giving us assurance that they at least compile and therefore likely run, the Wasm `browser` and `node` examples are not parsed at all. This leads to silent breakages when any exported symbols change that can go unnoticed for some time.

A periodic task similar to the `audit` task might be appropriate as the examples can sometimes fail intermittently and take a long time to execute. Adding them to the `build-and-test` task would detect breakages more quickly and identify the exact set of changes responsible, but likely result in more false-positives along with slowing down the CI overall.

Maybe add the Wasm README.md examples (#342) to the same task once they are runnable?

## Resources
- related to https://github.com/iotaledger/identity.rs/issues/342

## To-do list

- [x] Add GitHub Actions task to build and run examples - PR #345

## Change checklist

- [x] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [x] The feature or fix has sufficient testing coverage
- [x] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
