### ISSUE TITLE
[Task] Rename `SecretKey` to `PrivateKey`

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#349]
## Description
Replace all usages of the term `SecretKey` with `PrivateKey`, and "secret key" with "private key" where appropriate.

## Motivation
It was raised on Discord that "secret key" usually refers to symmetric cryptography, while we use it in an asymmetric context, with `PublicKey` and `SecretKey` part of `KeyPair`. Thus to avoid confusion it should probably be renamed.

Renaming it would align with the nomenclature and the term `PivateKey` is more often used than `SecretKey` in other projects in the organisation. There doesn't seem to be a particular reason to keep it as-is other than to avoid a breaking change, which is not a major concern as `identity.rs` is pre-1.0.

This is a low-priority issue, just placing it here to avoid forgetting it. 

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Rename `SecretKey` to `PrivateKey`
- [ ] Update comments, documentation

## Change checklist

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
