### ISSUE TITLE
Improve Support for Private Tangle

### ISSUE THREAD

**Issue by abdulmth** [iotaledger/identity.rs#355]
## Description
Creating a configuration for Private Tangles should be improved and follow similar steps as configuring Mainnet or Testnet.

## Motivation
A `Network` object can't be configured for networks other than Mainnet or Testnet. 

## To-do list
- [ ] Improve the `Network` class to be configured for private tangles.
- [ ] Add an example for a private tangle configuration.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
