### ISSUE TITLE
[Task] Update testnet to devnet 

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#358]
## Description

We currently are using the Chrysalis P2 testnet as secondary network besides the mainnet. This will be discontinued in favour of the Chrysalis P2 devnet. This means we need to update default explorer URLs, default node urls, update method spec to use `did:iota:dev` and update references to devnet.

## Resources
Link to any resources relevant for the task such as Issues, PRs, reference implementations, or specifications.

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Update default testnet explorer URL to devnet
- [ ] Update default testnet node URL to devnet
- [ ] Update method spec
- [ ] Change any references to testnet to be devnet

**Comment by cycraig** [comment]
The explorer currently still displays the `testnet` instead of the `devnet`. As we rely on the explorer URL in our code for linking to messages and the recent resolver URL, it's probably best to wait for it to be updated.

Users are still able to use the `devnet` by manually creating a network with the appropriate node address.

**Comment by cycraig** [comment]
Looks like the testnet node is offline as trying to use it causes the following error:
```
Error [ClientError]: Response error with status code 503: Service Unavailable
```

Not sure if this is temporary or not but we may have to push through the change without the explorer update.

**Comment by cycraig** [comment]
Update: [explorer updated to `devnet`](https://explorer.iota.org/devnet). This issue should be addressed as soon as possible now.

**Comment by cycraig** [comment]
Resolved in #405.
