### ISSUE TITLE
[Task] Convert Account to handle one Identity

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#431]
## Description
Describe the task, this may be scoped beyond a single PR.

The `Account` has been used to handle multiple identities and therefore has some complex logic. This is more application level behavior and therefore is not the responsibility of this framework. The challenge for this PR will be around cleaning up the  account configurations as these can be shared between multiple accounts. Similarly the `Storage` mechanism needs to be sharable between multiple accounts by using something like `Arc<dyn Storage>`, meaning the account doesn't control a `Storage` itself, but rather a reference to it. 

In addition, the PR should tackle and question the need for a `Config`, `State` (which has the `ClientMap`) and a `store` (which is the `Storage`) and combine them into something more clear and easier to handle across multiple accounts. Lastly, it should also be checked that two different accounts can use different configurations, but share a storage mechanism. For example Account A uses Config A, Account B copies Config A into Config B, and changes the `ClientMap`, in this case the Storage would be the same. 

This Issue does NOT have to take care of any `factory`, `builder` or whatever pattern we decide for to create multiple accounts, but needs to prepare for the future existence of such a feature by having these configurations comply to the above requirements. 

## Motivation

Cleaner Account API and better maintainable code. 

## Resources
Link to any resources relevant for the task such as Issues, PRs, reference implementations, or specifications.

- [Github Discussion](https://github.com/iotaledger/identity.rs/discussions/396).

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [x] Remove IdentityIndex
- [x] Improve API and implementation to utilize that the `Account` now only has one identity
- [x] Update `IdentityUpdater` to no longer require an identifier in its updating process.
- [x] Clean up `configurations`
- [x] Make sure multiple `Accounts` can share the same `Storage`.
- [x] Remove the `find_identity`, `list_identities` and `resolve_identity` methods.
