### ISSUE TITLE
[Task] Validate need for autosave functionality in Account

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#432]
## Description

As part of the Account Configuration and the Builder, the developers are able to set three different options for `AutoSave`: Every, Batch(x) and Never. This determine if how frequently local changes to a DID Document are stored in the `Stronghold` or other Storage adapter implementations. This feature might reduce write-to-disk operations, which could have a significant impact on performance. It may be that this feature is also implemented on a Stronghold level. Additionally, such as optimization might be better suited on the application level. 

The task of this Issue is to compare the performance of using the different settings, using `Stronghold` as the Storage target. In addition, based on the results and the general discussion in this Issue, it has to be determined if this feature remains part of the Account or will be removed before 1.0. 

## Motivation

Clean up the API of the Account by revisiting certain settings that might not be best suited for the framework. 

## Resources

* @felsweg-iota might be willing to help with providing input on `Stronghold` best practices in regards to minimizing write-to-disk operations. 

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Benchmark different `AutoSave` settings with `Stronghold`
- [ ] Discuss the conclusions in this Issue
- [ ] Implement outcome (Remove feature or keep and close)

**Comment by felsweg-iota** [comment]
Generally speaking disk I/O would only be involved when exporting snapshots out of Stronghold's current state.  

Some remarks (and questions): 
- Changes to the account are frequently written out as snapshot; Stronghold could keep all entries securely in memory, writing the desired state to disk on `drop(self)`, if it's possible to keep identity running. 
- If I understand it correctly, the question is if Stronghold is being used as persistence layer complementing [`MemStore`](https://github.com/iotaledger/identity.rs/blob/833cf05b489c739cf59df6cc9d1b29b35b801763/identity-account/src/storage/memstore.rs#L44)?

**Comment by felsweg-iota** [comment]
Hey @JelleMillenaar , the current implementation of Stronghold does no extra queue, as a heuristic would be needed to determine the best time to write. However, It would be possible to memory map any underlying snapshot. See [mmap](https://docs.rs/memmap/0.7.0/memmap/struct.MmapMut.html) crate for some examples. Another possibility could be streaming into a memory mapped snapshot. 

This implementation would be quite low-level for Stronghold though.

**Comment by felsweg-iota** [comment]
@PhilippGackstatter yes you are correct. Only the calls to the snapshot functions will invoke disk I/O.

**Comment by HenriqueNogara** [comment]
As a reference; Performing 100 actions with multiple `AutoSave` settings, performed as expected. Meaning that the more often we save the snapshot, the less efficient it is. 

Benchmark code: 
```Rust
async fn multiple_identity_updates(auto_save: AutoSave, actions: usize) {
  let mut builder: AccountBuilder =
    Account::builder()
      .autopublish(false)
      .autosave(auto_save)
      .storage(AccountStorage::Stronghold(
        rand_string(10).into(),
        Some(rand_string(10).into()),
        Some(false),
      ));
  let account: Account = builder.create_identity(IdentitySetup::default()).await.unwrap();

  for _ in 0..actions {
    account.increment_actions();
    account.save(false).await.unwrap();
  }
}
```
Results: 

| Batch  | Averagetime (ms) | 
|----------|:-----------------------:|
| Never|  305 |
| Batch(100) |   311   |  
| Batch(50)  | 312 |  
| Batch(20)  | 319 |  
| Batch(10)  | 328 |  
| Batch(5)  | 337 |  
| Batch(2)  | 395 |  
| Every  | 510 |
