### ISSUE TITLE
[Task] Refactor the Account state

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#433]
Note: This issue used to be about low-level API access, but this task has moved to #475.

## Description

Refactor the `Account` state to enable lower-level access (#475) to the document stored inside. This should refactor the account snapshots with its event system to use `IotaDocument`s to represent the state of an identity. The stored document represent the last resolved tangle state of the document. When an account is created, this document is loaded and any updates to the identity are applied to that in-memory document.

Whether these updates are written into storage or stay temporary until published needs to be figured out. Doing so would enable updates to be applied to the identity locally, and publish them at a later point. The downside is the higher complexity involved, since the low-level access to the document isn't explicit to the account, so it cannot write them into storage immediately. Some caveats may apply in that case.

Finally, the refactor should introduce an abstraction that allows for easier implementation of future did methods.

## Motivation

Simplify the internal state representation and take advantage of the account only having to manage one identity now.

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Remove `IdentitySnapshot` and the event/commit system
- [ ] Upgrade `IotaDocument` with any better APIs from `IdentityState`
- [ ] Replace the internal state with an `IotaDocument` and apply all updates to that document
- [ ] Abstract identity management into an interface
