### ISSUE TITLE
[Task] Research (and impl) DID Message Compression to reduce Message size

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#434]
## Description

As of right now, DID Messages are published as a JSON formatted document containing (parts of a) DID Document and metadata. As the size of messages on the Tangle, directly influences the Proof-of-Work requirement, it is important to reduce the amount of data on the Tangle, while not losing any information. You might call something like that lossless compression 😄 

Two things need to be considered for compression and may be combined if it achieves the best outcome:
* Lossless Compression Algorithms
* Handmade Compression 

A handmade compression could be a "conversion map" (Not sure if this is a thing), where we map frequently used fields to smaller, often single, characters. DID Messages contain valid JSON, but technically speaking we could map `"verificationMethod":` to `v:`. This may already be caught by the lossless compression algorithm, but I expect a combination to net the best results. 

Any compression will remove the human-readability from the Tangle messages. It will be important to decompress messages in an early stage of the processing, such that no tools are broken (Identity Resolver). 

It was already the idea to add version to the DID messages in order to have the ability to support backwards compatibility. This would need to be a field outside of the compression as a new version could also indicate a new compression / decompression algorithm in the future. 

## Motivation

Reduce DID Messages size, therefore reducing the Proof-of-Work requirement for IOTA Identity, increasing the speed of the framework's writing ability and reduce the carbon footprint. 

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Compare Lossless Compression Algorithms
- [ ] Implement Handmade Compression
- [ ] Compare in combination with Handmade Compression
- [ ] Introduce DID Message version outside of compressed region

**Comment by abdulmth** [comment]
### Comparing Lossless Compression Algorithms

For compressing a DID message, the following algorithms has been tested: 

* Bzip2: uses file extension `.bz2`, initial release in 1996, usually more effective than deflate.
* zlib: abstraction of the DEFLATE compression algorithm, initial release in 1995.
* Snappy, aims for speed more than maximum compression, developed by Google, initial release 2011.
* Brotli: works best for text compression, developed by Google, initial release 2013.

`{"id":"did:iota:U1zDCC47hjcXupixrw5kbKCxV3ZCUn3RomJ5VkX1wHv","verificationMethod":[{"id":"did:iota:U1zDCC47hjcXupixrw5kbKCxV3ZCUn3RomJ5VkX1wHv#authentication","controller":"did:iota:U1zDCC47hjcXupixrw5kbKCxV3ZCUn3RomJ5VkX1wHv","type":"Ed25519VerificationKey2018","publicKeyBase58":"Mamni7dcVHSDvyAHy4MLFaYTDqh2upJJWca4yqF82yb"}],"authentication":["did:iota:U1zDCC47hjcXupixrw5kbKCxV3ZCUn3RomJ5VkX1wHv#authentication"],"created":"2021-10-21T09:37:56Z","updated":"2021-10-21T09:37:56Z","proof":{"type":"JcsEd25519Signature2020","verificationMethod":"#authentication","signatureValue":"M4qQSeVBRXCumiCqA6hNNcb6xBVmtdGD7tgAvDfTPfPjwRfYof8ZUBihwdEhmD6jDTcWpSanWDWJKsxc1yK5gUo"}}
`
#### Compression Ratio (in percent, higher is better)


| Bzip2    | zlib     | Snappy   | Brotli|
| -------- | -------- | -------- | ----- |
| 33.1     | 49.0     | 35.4     | 52.2  |


---

#### Compression Speed
Compressing the input string 10.000 times (in seconds, lower is better)


| Bzip2    | zlib     | Snappy   | Brotli|
| -------- | -------- | -------- | ----- |
| 3.05     | 3.93     | 0.54     | 5.41  |

---

#### Decompression Speed
Decompressing the input string 10.000 times (in seconds, lower is better)

| Bzip2    | zlib     | Snappy   | Brotli|
| -------- | -------- | -------- | ----- |
| 0.72     | 2.37     | 0.16     | 0.18  |

---
I'm leaning towards Brotli since it's gives the best compression ratio and decompresses very fast. Although it has the highest compression time, it should be a fine compromise since it will be compensated by less time spent on PoW and usually only one message is compressed at a time 🤔. 

So far I have a few questions: 
* Is there other algorithms you're aware of that I should test?
* Is the input string good enough as a measurement base?


---
## Versioning
A simple versioning approach could be by reserving the first line to version/metadata. e.g.:
```
DIDV1
<compressed bytes>
```
