### ISSUE TITLE
[Task] Clean up previous DIDComm impl

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#437]
## Description

Remove older DID Comm protocols that do not align with our new specification. 

## Motivation

Fresh start

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [x] Clean up `identity-comm/src/messages` and `identity-comm/src/tests`
- [x] Clean up `bindings/wasm/src/message`
- [x] Other places reverencing older DID Comm protocols.

**Comment by olivereanderson** [comment]
I think https://github.com/iotaledger/identity.rs/pull/467 and https://github.com/iotaledger/identity.rs/pull/468 takes care of the first two items on the To-do list, but I might have missed something.
