### ISSUE TITLE
[Task] Move existence checks for methods to the lower-level API

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#495]
## Description

The account currently checks for the existence of a method before adding or removing it, to avoid adding a duplicate method or attempting to remove a method that does not exist. Similar checks are done before attaching or detaching verification relationships. These checks should be moved to the lower-level `IotaDocument` or `CoreDocument`, to prevent users from creating invalid documents.

## Motivation

Prevent users from creating invalid documents.

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] `UpdateError`: Move variants to the lower-level crates if appropriate, like `MethodNotFound` or `InvalidTargetEmbeddedMethod`
- [ ] create method: Add check to ensure no method with the same fragment already exists.
- [ ] delete method: Add check to ensure that method with the given fragment exists.
- [ ] attach relationship: Improve returned error two handle the two cases of 1) method does not exist and 2) method exists but is embedded properly, similar to the below snippet

```rust
    if let None = self.resolve_method_with_scope(method_query.clone(), MethodScope::VerificationMethod) {
      match self.resolve_method(method_query) {
        Some(embedded) => return Error::InvalidTargetEmbeddedMethod,
        None => return Error::QueryMethodNotFound,
      }
    }
```

Note: Keep attach/detach relationship idempotent, i.e. attaching a relationship, if the relationship already exists, succeeds, while detaching a non-existent relationship also succeeds.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
