### ISSUE TITLE
[Task] Detect and abort publishing if document is outdated

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#497]
## Description

We support distributed setups, where multiple accounts, e.g. on different machines, can update the same identity. One of those accounts can make updates to a locally stored document, without publishing them (e.g. with `autopublish = false`). If one of them updates an outdated locally cached document we should ideally detect that case before publishing and abort.

## Motivation

Better support distributed setups.
## To-do list
Create a task-specific to-do list. Please link PRs that match the To-do list item behind the item after it has been submitted.

This list proposes a mechanism for implementing re-application of updates in the IOTA Chrysalis DID method, it is left here for reference.

- [ ] Detect the outdated case during publication and return an error.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
