### ISSUE TITLE
[Task] Support challenges in Verifiable Presentations

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#498]
## Description
Add support for the `challenge` field in Verifiable Presentation proofs. 

This could be expanded to allow `challenge`, `domain`, and `proofPurpose` (or arbitrary fields) in any `proof` section.

## Motivation
The Verifiable Presentation specification allows the presenter to include `challenge` and `domain` fields from a verifier in the `proof` section of a presentation which are signed along with the rest of the data. These fields are meant to be unique per presentation and per verifier to help mitigate replay attacks.

Currently, our presentations do not allow adding these fields since the signing process completely overwrites the `proof` section contents. Working around this means either including `challenge`/`domain` as part of the base content rather than the `proof` section, which may not comply with the specification, or writing a signing implementation that does not replace those fields.

## Resources
- Example with the `challenge` and `domain` fields: https://www.w3.org/TR/vc-data-model/#example-a-simple-example-of-a-verifiable-presentation
- Schema for properties allowed in signatures: https://www.w3.org/TR/vc-data-model/#base-context
- Definition of security property fields (`challenge`, `domain`, `proofPurpose`, `expires`): https://w3c-ccg.github.io/security-vocab/#

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Support `challenge`, `domain`, `expires`, `proofPurpose` as part of signatures (either generically or for presentations only).
- [ ] Validate `expires` and expected `challenge`, `domain`, `proofPurpose`.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by cycraig** [comment]
The base context defining fields allowed in signatures are defined in the Verifiable Credential specification: https://www.w3.org/TR/vc-data-model/#base-context

Most relevant is the `Ed25519Signature2018` schema.

```json
"Ed25519Signature2018": {
  "@id": "https://w3id.org/security#Ed25519Signature2018",
  "@context": {
    "@version": 1.1,
    "@protected": true,

    "id": "@id",
    "type": "@type",

    "sec": "https://w3id.org/security#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",

    "challenge": "sec:challenge",
    "created": {"@id": "http://purl.org/dc/terms/created", "@type": "xsd:dateTime"},
    "domain": "sec:domain",
    "expires": {"@id": "sec:expiration", "@type": "xsd:dateTime"},
    "jws": "sec:jws",
    "nonce": "sec:nonce",
    "proofPurpose": {
      "@id": "sec:proofPurpose",
      "@type": "@vocab",
      "@context": {
        "@version": 1.1,
        "@protected": true,

        "id": "@id",
        "type": "@type",

        "sec": "https://w3id.org/security#",

        "assertionMethod": {"@id": "sec:assertionMethod", "@type": "@id", "@container": "@set"},
        "authentication": {"@id": "sec:authenticationMethod", "@type": "@id", "@container": "@set"}
      }
    },
    "proofValue": "sec:proofValue",
    "verificationMethod": {"@id": "sec:verificationMethod", "@type": "@id"}
  }
}
```

Many of the properties are defined in https://w3c-ccg.github.io/security-vocab/#

Notable:
- [challenge](https://w3c-ccg.github.io/security-vocab/#challenge)
- [domain](https://w3c-ccg.github.io/security-vocab/#domain)
- [expires](https://w3c-ccg.github.io/security-vocab/#expiration)
- [proofPurpose](https://w3c-ccg.github.io/security-vocab/#proofPurpose) (unclear if it's restricted to only "assertionMethod" and "authentication")
