### ISSUE TITLE
[Task] Reject/filter diff updates with signing key changes

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#499]
## Description
Filter out diff updates that contain changes to verification methods able to update the DID Document during resolution.

## Motivation
[The IOTA DID Method Specification states](https://wiki.iota.org/identity.rs/specs/did/iota_did_method_spec#anatomy-of-diff-did-messages):

> A Diff DID message is NOT allowed to add, remove or update any signing keys. This must be done via an Integration DID message. 

The diff chain currently does not enforce this requirement and applies diff updates during resolution that may alter the capability invocation method set in the DID Document. This can lead to situations where a resolved DID Document is in an improper state as replacing the signing keys in diff update/s then trying to publish a new integration chain update will cause it to be rejected, as it would not be signed with any of the keys present in the previous integration chain message.

## Resources
IOTA DID Method Specification: 
- Diff DID Messages: https://wiki.iota.org/identity.rs/specs/did/iota_did_method_spec#anatomy-of-diff-did-messages
- Signing Keys: https://wiki.iota.org/identity.rs/specs/did/iota_did_method_spec#signing-keys

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Update `DiffChain` to reject updates that alter the set of signing keys

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
