### ISSUE TITLE
[Task] Derive `KeyLocation` from inherent fields of methods

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#508]
## Description

Refactor the `KeyLocation` to remove their dependence on generations. The generations currently ensure that two keys with the same fragment can co-exist. To allow co-existence in the future, we can base the key location on the fragment _and_ a hash of the `MethodData`. Two keys with different key materials can share the same fragment without producing the same location. This enables us to derive the key location entirely from the document and does not require additional state keeping.

This can be implemented once https://github.com/iotaledger/stronghold.rs/issues/283 is implemented. Prior to that, we need to migrate to the newer stronghold version, which has a refactored procedure API and refactored error types.

## Motivation

The locations are the last remaining place where generations are needed in the account. To reduce complexity and the amount of state to keep, we want to get rid of the generations.

## To-do list

This issue can be implemented in two separate PRs.
- [ ] Refactor the `KeyLocation`s
    - [ ] Base the `KeyLocation` on fragment and a hash of `MethodData`.
    - [ ] Make use of the new key migration feature in stronghold to allow generating a key in stronghold and migrating it to a location based on its public key (`MethodData`).
    - [ ] Update `CreateIdentity` and `CreateMethod` to make use of this feature, in particular the initial DID generation.
    - [ ] Remove the `IdentityState` (which includes the generations).
    - [ ] Implement `Storage::purge` for `MemStore` and `Stronghold`
    - [ ] Implement deletion of keys of deleted verification methods (while being careful with methods that are used to sign the update that removes that method).

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
