### ISSUE TITLE
[Task] Refactor `Account` to use a single `Client`

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#531]
## Description
Replace the `ClientMap` in `Account` with a single `Client`.

## Motivation
With the `Account` refactor to handle a single identity per instance in #436 and #453, it makes more sense for each `Account` to use a single `Client` instead of a shared `ClientMap`, given that each identity is linked to a single network (devnet, mainnet, or a private Tangle). There is no longer a need for an `Account` to resolve from or publish to more than one network now.

This would avoid the possibility of subtle bugs that can occur due to `Account`s from the same `AccountBuilder` sharing an `Arc<ClientMap>` where clients for private networks can be overwritten.

This may also open up the `ClientMap` to a refactor for use in a new `Resolver` API #493.

This can still be discussed.

## To-do list

- [ ] Replace `Account::client_map` with a single `Client`

## Change checklist

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by PhilippGackstatter** [comment]
Generally, I agree with removing the `ClientMap` because an account only works with a single network. The question is, should we already do this, or wait until we have something like a `ClientSet`? This might end up being a single `Client`, which can choose from a number of node urls. How that `ClientSet` is passed node urls will probably concern the `AccountBuilder`, that's why we may want to hold off on this for now? Just a thought to avoid refactoring twice.

**Comment by cycraig** [comment]
I'm not clear on what a `ClientSet` would be and what problem it would solve? I think the `Client` already supports adding multiple nodes simply by wrapping `iota-client`.

**Comment by PhilippGackstatter** [comment]
In that case, my point is moot. This could be an additional task item in the issue then, "Enable users to set node urls (and perhaps quorums?) in the `AccountBuilder`".

**Comment by cycraig** [comment]
It looks like the `ClientBuilder` already has a lot of options for nodes and quorums, e.g.

```rust
  /// Enables/disables quorum.
  pub fn quorum(mut self, value: bool) -> Self {
    self.builder = self.builder.with_quorum(value);
    self
  }

  /// Sets the number of nodes used for quorum.
  pub fn quorum_size(mut self, value: usize) -> Self {
    self.builder = self.builder.with_quorum_size(value);
    self
  }

  /// Sets the quorum threshold.
  pub fn quorum_threshold(mut self, value: usize) -> Self {
    self.builder = self.builder.with_quorum_threshold(value);
    self
  }
```

Would it be sufficient to use the `ClientBuilder` to build a `Client` then pass it to the `AccountBuilder`? Or do we want all those options in the `AccountBuilder` itself for ease-of-use?

**Comment by PhilippGackstatter** [comment]
I probably slightly prefer using the `ClientBuilder` directly. That seems sufficient since there are quite a few options we would or could duplicate on the `AccountBuilder` and that starts to look like API pollution. We could still go with the `client` option we already have on the `AccountBuilder`, but I think that was generally disliked?

**Comment by cycraig** [comment]
Right, I dislike how the current `AccountBuilder::client` works since it requires a closure. It was for multiple networks/clients so that can be removed anyway.

**Comment by abdulmth** [comment]
This issue is probably important to be done for the Account WASM bindings.
