### ISSUE TITLE
[Task] Remove old resolution module

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#532]
## Description
~The `identity-did/resolution` module should be split into its own crate, e.g. `identity-resolver` or `identity-resolution`.~

Edit: the `identity-did/resolution` module should be removed.

## Motivation
The module for DID specification-compliant resolution and dereferencing in `identity-did/resolution` is largely unused right now and distinct from the rest of the codebase. ~It's useful for a universal resolver in the future so we should at least retain the code.~

Edit: there doesn't seem to be a reason to keep the code anymore, a universal resolver can be implemented easily without this.

## Resources
https://www.w3.org/TR/did-core/#resolution

## To-do list

- [ ] ~Move `identity-did/resolution` into its own feature-gated crate.~
- [ ] Remove `identity-did/resolution` and all associated code.

## Change checklist

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by cycraig** [comment]
Update: it was decided to remove the old resolution code entirely.
