### ISSUE TITLE
[Task] Storage Example

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#538]
## Description

While we recommend Stronghold as storage, it is natural that application developers may already have a solution to handle secrets and cryptographical operations. As such, we the account has been made to have flexible storage mechanism, where developers may plug-in their own storage solution. We yet lack an example on how to implement the Storage and introduce it to framework. Nor do we have documentation (wiki page) on how this works. 

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Implement Storage Example Rust (Weakhold  - serialize to JSON file)
- [X] Provide content for the Storage Adapter section on the wiki
- [X] WASM bindings https://github.com/iotaledger/identity.rs/pull/681
- [X] WASM Example for Storage (Pure JS-Implementation) (Perhaps in a 2nd PR) https://github.com/iotaledger/identity.rs/pull/681

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by eike-hass** [comment]
Decided to not implement a Weakhold since it would not follow security best practices.
