### ISSUE TITLE
[Task] Add MerkleKeyCollection support to Account

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#539]
## Description

Their is currently no account support for adding a Merkle Key Collection, without going through the low-level API. Merkle Key Collections are a critical part of functionality that we expect to be used frequently. Adding the logic to the Account API will be crucial yet also challenging due to its flexible and complex behavior. The API should be able to add a collection, remove collection, revoke keys and sign with a key from a collection.

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Design new API
- [ ] Implement new API
- [ ] Account Example

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by PhilippGackstatter** [comment]
There's a myriad of issues to solve before @abdulmth and I can start the implementation, so I'm hoping we can fix at least a direction of how to approach it.

1. `KeyCollection` fundamentally assumes that it holds the private keys, which is completely incompatible with private keys living in storage in the account.
2. The known issue of not being able to call an `async` remote signature implementation, like `RemoteEd25519` from a sync trait like `Signer`.
3. `IotaVerificationMethod::create_merkle_key` taking a `KeyCollection`, which is not going to work out of the box if we have to add a second `RemoteKeyCollection` type.
4. `Account::sign` taking only the fragment for a method to sign with, leaving the key with which to sign unclear in the case of a key collection.
5. `MethodType::MerkleKeyCollection2021`  not specifying what signature the key from the collection is actually using, or what hash.
6. The size of the collection is unknown when creating it from storage.

To address these, this is just a **proposal**, feel free to comment and suggest alternatives.

- Don't make storage implementations support key collection directly, because that would require storage impls to duplicate a lot of code. Instead, since a collection is just a bunch of keys, like `Ed25519`, that storages like stronghold already handle, we build on top of that.
- The `KeyCollection` type from the core crate holds the private keys directly, and because of that will not work with remote keys, i.e. those stored in storage. Instead, introduce a `RemoteKeyCollection` that has probably just a reference to storage (`&dyn Storage` or `Arc<dyn Storage>`). The merkle root can be lazily computed by retrieving all the public keys from storage. This might be fairly bad for large collections, so that has to be tested. The alternative is to compute the root once on creation, since it stays the same for the duration of any given key collection, and cache it in storage. Not terrible, but requires additional management of that state, like deriving a location for it and deleting it at some point. Storing arbitrary data in a storage is also not supported currently, so we either add that functionality or add a dedicated storage method for storing that root. Because of that, I'd prefer to lazily compute it, if performance allows for it.
- Introduce an `async` `RemoteSign` trait, which only `RemoteEd25519` implements (for now). The existing traits in core are simply not suitable for the account, because they take private keys as parameters.
- Change `IdentityState::sign_data` to take a `&dyn RemoteSign`, instead of a `KeyLocation` and `&dyn Storage`, mostly to delegate the concrete sign implementation to `RemoteSign` rather than deciding on that in `sign_data`.
- `Account::sign` delegates to `sign_data` like before, but returns an error if the passed fragments resolves to a verification method with `MethodType::MerkleKeyCollection2021`. This is necessary, because of problem 4.
- Introduce `Account::sign_from_collection` (or something) that has the same signature as `Account::sign`, but also takes an `index: usize` that identifies one key in the collection. If the type of the resolved method is anything but `MethodType::MerkleKeyCollection2021`, it returns an error. We extract the tag from the merkle key to get the signature and hash types, and instantiate the corresponding `RemoteSign` implementation. For now, we only need to map `MerkleSignatureTag::ED25519` to `RemoteEd25519`, and then produce a key collection signature. This will involve calling the `RemoteSign` impl and creating a new `RemoteKeyCollection` to compute a proof of inclusion for the public key that was used (`index`).
- In order to create a verification method that uses a key collection, we likely have to refactor `IotaVerificationMethod::create_merkle_key`, to take an encoded merkle key instead of a `KeyCollection`. This merkle key is currently a `Vec<u8>`, but because we don't want to take a `Vec<u8>` here, we can consider refactoring the existing `MerkleKey` to be a thin wrapper around `Vec<u8>`.

There's a somewhat related issue. Deriving `KeyLocation`s as planned in #508 does not work exactly like that for key collections. The proposal, in short, is to use `{fragment}{hash(method_data)}` as the key location. While we can use a similar approach, we also need to add the index of each key, because each key is going to be at an individual location. So basically `{fragment}{publicKeyMultibase}{key_index}`. This way, we only need to know an index and can derive the location for that key. 

Technically, we don't need to know the size of the collection, as we could start iterating from 0 and look up public keys until we no longer find any, and if the total size is not a power of 2, return an error. But that seems pretty hacky. I would prefer storing the size of the collection. To do so, we could:

1) Keep the size of a key collection in the storage.
2) Add size property as a `verificationMethod` field.
3) Encode the size into the `publicKeyMultibase` like we do with the hash and signature type: `U8(log2(KEY-COLLECTION-SIZE)) || U8(SIGNATURE-TAG) || U8(DIGEST-TAG) || BYTES(MERKLE-ROOT))`. (We could get away with just an additional byte, as long as we're comfortable enforcing collection sizes to be powers of 2 in the future, which I think we are?)

2 and 3 would be the stateless options, and would not require invoking storage to create a `KeyLocation`. As long as revealing the size of the collection is not considered an information leak, this seems like a good way to go. 2 however seems like a way to break encapsulation, because now the `IotaVerificationMethod` needs to parse that field, but it's only relevant for key collections. So 3 is my preference.

This also requires a refactor of `KeyLocation`, because key collections would have different inputs to their location, so ideally we simply have two constructors for `KeyLocation`, one for regular keys and one for key collections.

Lastly, if we implement all this before #508, then we can probably just abuse the `KeyLocation::generation` field as the index of the key.

Sooo, any thoughts on this? If no one has the time to dive deep into this, from my point of view, it's also fine to just start with this and see where we get. Most likely, more issues will come up anyway.

**Comment by PhilippGackstatter** [comment]
@abdulmth would like to get started with this issue, so here's a more helpful first part to implement.

```rust
pub struct RemoteKeyCollection {
    storage: Arc<dyn Storage>,
    fragment: Fragment,
    len: usize,
}
```

This type should mimick the `KeyCollection` API as closely as possible. Good first methods to implement are: `KeyCollection::{new, public, merkle_root, merkle_proof, encode_merkle_key}`. Any methods that return a private key like `KeyCollection::{private, keypair, iter_private}` are not possible to port.

- To implement the `merkle_*` methods, it will make sense to re-use the functionality from the core crate like `compute_merkle_root` and `compute_merkle_proof`.
- To implement the `new` method, we will have to generate new keys. Examples for key generation in the storage are in `identity_account::updates::update::Update::process` in the implementation arm for `CreateMethod`.
- To store the keys, we need to create a `KeyLocation`. The `MethodType` can be ignored for the initial implementation, e.g. we can use `MethodType::MerkleKeyCollection2021`, even though that makes no sense (that key alone is not a collection).
- We can generate the fragment and generation for the `KeyLocation`s based on the `index` of the key we're generating, e.g. `KeyLocation::new("key-collection-fragment".to_owned(), Generation::from_u32(index))`.

Hopefully that helps getting started.

**Comment by cycraig** [comment]
Might be made irrelevant by https://github.com/iotaledger/identity.rs/issues/715.

**Comment by cycraig** [comment]
No longer an issue: `MerkleKeyCollection` was removed in #715.
