### ISSUE TITLE
[Task] Replace `ChainState` in `Account`

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#542]
## Description
Once #540 lands we should investigate whether the `ChainState`, which tracks the last integration and diff message IDs, can be replaced by the `ResolvedIotaDocument`.

## Motivation
This would slightly simplify the `Account` internals.

## To-do list

- [ ] Determine if `ChainState` can be replaced.
- [ ] Replace `ChainState` with `ResolvedIotaDocument`.

## Change checklist

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by cycraig** [comment]
The diff chain is still sticking around for a while longer, we can revisit removing `ChainState` at a later date.
