### ISSUE TITLE
[Task] Remove `AccountStorage`

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#552]
## Description

Remove `AccountStorage` and encourage users to build types that implement `Storage` directly, and inject that into `Account`s or `AccountBuilder`s. 

## Motivation

As discussed in [PR 500](https://github.com/iotaledger/identity.rs/pull/500#discussion_r756859344), `AccountStorage` could be removed to avoid the duplicate ways of constructing `Storage` types. This problem gets worse when options to the storage are added, like `dropsave` for `Stronghold`. With the anticipated addition of a `RemoteStronghold`, which will probably have a number of options, it seems to make sense to get rid of `AccountStorage`.

Another reason is that one less type needs to be exposed to the bindings.

## Resources

The [discussion](https://github.com/iotaledger/identity.rs/pull/500#discussion_r756859344) where the issue came up.

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Remove `AccountStorage`.
- [ ] Introduce a `Stronghold::new` constructor that uses defaults for the options (`dropsave` = `true`)
    - Move the logic to build stronghold from `AccountBuilder::get_storage` into the constructor, if appropriate/necessary.
- [ ] Add a `Stronghold::new_with_options` constructor that also takes a `StrongholdOptions` struct, which only contains `dropsave` for now, but can be expanded in the future with more options.
- [ ] Decide whether `AccountBuilder::storage` should take `impl Storage` or `Arc<dyn Storage>`.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
