### ISSUE TITLE
[Task] Complete WASM bindings for `IotaDocument`

### ISSUE THREAD

**Issue by abdulmth** [iotaledger/identity.rs#622]
## Description
Write Wasm bindings in `WasmDocument` for all unported public functions in `IotaDocument`

## Motivation
Some functionalities in `IotaDocument` were introduced but not yet ported. for example `attach_method_relationship(..)`

## To-do list

The following methods are yet to be ported from `IotaDocument`:

- [ ] `is_signing_method_type` 
- [ ] `controller`
- [ ] `also_known_as`
- [ ] `properties/properties_mut` - we might need a convenient way to add/edit/remove arbitrary properties in Wasm besides using `toJSON`, editing it there, then converting back with `fromJSON`?
- [ ] `service`
- [ ] `methods`
- [ ] `attach_method_relationship`
- [ ] `detach_method_relationship`
- [ ] `resolve_method_with_scope` - maybe we can just add an optional `WasmMethodScope` parameter on `WasmDocument::resolveMethod`?
- [ ] `resolve_signing_method`

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by cycraig** [comment]
I added the differences in the To-do list. Unclear whether some were intentionally not ported if they can be accessed via JSON, e.g. `services`, `methods`, and `properties`.

Left out certain methods like `signer` (since we don't want to port `DocumentSigner` to Wasm), `core_document` (Wasm doesn't have the distinction of an `IotaDocument` versus a `CoreDocument`).
