### ISSUE TITLE
[Task] Allow executing procedures from the stronghold wrapper

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#625]
## Description

Allow users to access the stronghold that is used as storage in the account. 

Ideally, this does not expose any of our internal stronghold functionality, but instead returns a clone or reference of the wrapped stronghold. Since the stronghold interface and architecture are undergoing changes, this issue can not be implemented right away.

The alternative would be to access the `Arc<dyn Storage>` of the account and downcast it. However, this is not possible without additional crates like downcast-rs, since only `Arc<dyn Any>` trait objects can be downcasted in the std library. Another way would be to expose our internal stronghold wrapper and the types associated with it, e.g. most of `identity_account::stronghold::*`, however this is undesirable as we have to commit to a public API that would mostly reimplement already exposed functionality in the public stronghold API. Thus, returning a clone/reference of some type of the stronghold API seems like the way to go.

## Motivation

This allows users to run procedures on a stronghold that are not exposed through the more general `Storage` trait. One example use case is running the X25519 Diffie-Hellman procedure within stronghold, rather than using a derived key in memory. This was requested by the IOTA streams team (cc @arnauorriols).

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Add a public getter on our `Stronghold` wrapper that returns a suitable type from the new stronghold interface that allows executing procedures

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by PhilippGackstatter** [comment]
The specific X25519 functionality that this was requested for originally is now part of the Account encryption API. Executing stronghold procedures from an `Account` is not generally possible since not every `Storage` is a stronghold, necessarily.
