### ISSUE TITLE
[Task] Implement a (universal) high level API for Credential validation 

### ISSUE THREAD

**Issue by olivereanderson** [iotaledger/identity.rs#631]
## Description
Provide an API to validate properties of verifiable credentials and presentations that are expected to be of interest to most applications. 

This includes verifying digital signatures, expiration dates, issuance dates, the nonTransferable property (in the case of Presentations) and (possibly) more.  The API does **not** need to validate every property specified [in the VC data model](https://www.w3.org/TR/vc-data-model/), but it would be nice if it allows for more validations to be added in the future in a backward compatible manner.  

## Motivation
This will relieve consumers of this framework from having to implement all credential and presentation validations themselves. 

## Resources
This is the outcome of discussion https://github.com/iotaledger/identity.rs/discussions/571. Its implementation will also close issues https://github.com/iotaledger/identity.rs/issues/312  and https://github.com/iotaledger/identity.rs/issues/295. A work in progress implementation can be found in this PR: https://github.com/iotaledger/identity.rs/pull/599. 

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [x] Provide a high level API with configurable options (PR: #599)
- [x] Provide an MVP for a lower level API consisting of simple validation units as defined in https://github.com/iotaledger/identity.rs/discussions/571 (PR: #599) 
- [x] Make the functionality available in the Wasm bindings (PR: #599)

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
