### ISSUE TITLE
[Task] Move `KeyComparable`, `OrderedSet` to `identity-core`

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#633]
## Description
Move the `OrderedSet` collection in `identity-did/utils` and its associated `KeyComparable` trait to `identity-core`.

## Motivation
It makes more sense to keep it in the same place as other generic structures like `OneOrMany`.

## To-do list

- [ ] Move `OrderedSet` to `identity-core/common`
- [ ] Move `KeyComparable` to `identity-core/common`

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by cycraig** [comment]
Doesn't work. `OrderedSet` has special implementations using `CoreDIDUrl` and `MethodQuery`. :disappointed:
