### ISSUE TITLE
[Task] Set `controller`, `alsoKnownAs` fields from `Account`

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#647]
## Description
Add update methods to the `Account` to allow setting the `controller` and `alsoKnownAs` fields.

## Motivation
The `IotaDocument` allows altering the `controller` and `alsoKnownAs` fields as part of the DID specification. We should expose this functionality in the `Account`, otherwise the only option currently is to perform an unchecked update, which is dangerous.

The exact design of the update methods is unclear. It may not be necessary to create four methods (create and remove operations for each field ) and instead just have two: `set_controller` and `set_also_known_as`? 

## To-do list

- [x] Allow setting `controller` on the `Account` #658
- [x] Allow setting `also_known_as` on the `Account` #658
- [x] Implement WASM bindings.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by cycraig** [comment]
Implemented in #658 for Rust, still TODO for Wasm bindings.
