### ISSUE TITLE
[Task] Improve `Account::attach/detach_method_relationship`

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#654]
## Description
Modify `Account::attach_method_relationship` and `Account::detach_method_relationship`:

- pluralise the names to match the Wasm bindings `Account`, i.e. `attach_method_relationships` and `detach_method_relationships`.
- allow specifying multiple relationships at once rather than individually, this would allow passing collections of relationships.

Current behaviour:
```rust
account
  .update_identity()
  .attach_method_relationship()
  .fragment("key1")
  .relationship(MethodRelationship::Authentication)
  .relationship(MethodRelationship::CapabilityInvocation)
  .apply()
  .await?;
```
Desired behaviour:

```rust
account
  .update_identity()
  .attach_method_relationship()
  .fragment("key1")
  .relationships(&[MethodRelationship::Authentication, MethodRelationship::CapabilityInvocation])
  .apply()
  .await?;
```

The `.relationships` implementation can either take a slice, vec, or arbitrary `IntoIter` generic depending on which we find is most convenient for developers to use.

We should also think about making attaching/detaching relationships easier for developers, since it is currently restricted to non-embedded methods. That is, trying to attach/detach an embedded method always causes an error, we could instead move the method to be a `verificationMethod`.

## Motivation
Porting the `Account` for the Wasm bindings in #574 demonstrated that using the builder pattern to add/remove multiple method relationships is cumbersome due to ownership/borrowing rules on intermediate structs. This issue is an attempt to make these specific methods more user-friendly and to reduce differences with the Wasm bindings.

## To-do list

- [ ] rename `Account::attach_method_relationship` to `attach_method_relationships`
- [ ] rename `Account::detach_method_relationship` to `detach_method_relationships`
- [ ] allow `Account::attach_method_relationships` to specify multiple relationships at once.
- [ ] allow `Account::detach_method_relationships` to specify multiple relationships at once.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
