### ISSUE TITLE
[Task] Upgrade stronghold to latest dev

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#661]
## Description

Upgrade to the latest stronghold version, revision `7bf15af8fc8770e06f1814cc61d3cae123553de8` at the time of writing.

## Motivation

To enable #508 this is a pre-requesite, since our current stronghold version does not allow for key copying.

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Map fine-grained stronghold errors to a stronghold error enum, respecting [the error guidelines](https://github.com/iotaledger/identity.rs/issues/534)

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by abdulmth** [comment]
Fixed in #691
