### ISSUE TITLE
[Task] Remove `DIDLease`

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#662]
## Description

Remove `DIDLease` from the `Account` and the `Storage` interface.

## Motivation

The `DIDLease` was originally added to prevent two accounts from concurrently modifying the same identity. It is now causing problems in the bindings due to the Wasm memory leak problem (which is a separate issue, to be fair), but also due to leases being a storage concern. Preventing this relatively rare bug comes at the cost of every storage implementation having to provide it. This issue could be solved by not exposing the `lease_did` function to the bindings storage interface (e.g. `WasmStorage`) and implementing it on the Rust side within the bindings. This is, at least as of now, not a solution due to Wasm memory leaks.

Another option would be to solve it on an `AccountBuilder` level, which would be better than not having it at all. However, creating a second `AccountBuilder` is even easier than using a second storage - which would also work around the check - and that potentially forgoes the check entirely.

Overall, it doesn't seem like preventing this rather niche bug seems worth the headaches it causes for bindings and storage implementors. Ultimately, this is an application concern.

## To-do list
Create a task-specific to-do list. Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Remove `DIDLease` from the storage implementations
- [ ] Remove `Storage:::lease_did`

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
