### ISSUE TITLE
[Task] Allow build-time configuration of local proof-of-work fallback

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#667]
## Description

Make use of the newly introduced `with_fallback_to_local_pow` on `iota_client::ClientBuilder` and expose this in our `ClientBuilder` as well.

## Motivation

Allow users to configure whether to fall back to local POW in cases where the remote does not support it.

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Expose a `local_pow_fallback` option on the `ClientBuilder`.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
