### ISSUE TITLE
[Task] Complete `Service` Wasm bindings

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#672]
## Description
Port all `Service` functions to the Wasm bindings.

## Motivation
Currently the Wasm bindings `Service` is incomplete:

```rust
#[wasm_bindgen]
impl Service {
  /// Serializes a `Service` object as a JSON object.
  #[wasm_bindgen(js_name = toJSON)]
  pub fn to_json(&self) -> Result<JsValue> {
    JsValue::from_serde(&self.0).wasm_result()
  }

  /// Deserializes a `Service` object from a JSON object.
  #[wasm_bindgen(js_name = fromJSON)]
  pub fn from_json(value: &JsValue) -> Result<Service> {
    value.into_serde().map(Self).wasm_result()
  }
}
```

This forces developers to rely on the `any` value returned from `Service.toJSON` to access of its constituent fields, and use JS objects to construct a `Service` using `Service.fromJSON`. 

E.g.

```ts
let serviceJSON = {
    id: doc.id + "#linked-domain-1",
    type: "LinkedDomains",
    serviceEndpoint: ["https://iota.org/", "https://example.com/"],
};
doc.insertService(Service.fromJSON(serviceJSON));
```

We should have a `Service` constructor that uses a duck-typed interface to define the required fields.

E.g.
```ts
let service = new Service({
  id: doc.id.toUrl().join("#linked-domain-1"),
  type: "LinkedDomains",
  serviceEndpoint: new ServiceEndpoint(["https://iota.org/", "https://example.com/"])
});
```
It's unclear right now if we should port `ServiceEndpoint` directly or rely on Typescript types. 
E.g. `string | string[] | Map<string, string>` or `string | string[] | Record<string, string>`

Note that this decision would influence the return type of `Service.serviceEndpoint` too, and it's unclear if we can return a duck-typed interface as easily, but we may have to anyway to get the contents of `ServiceEndpoint`?

## Resources
Link to any resources relevant for the task such as Issues, PRs, reference implementations, or specifications.

## To-do list

- [ ] Service constructor with duck-typed interface.
- [ ] Service fields getters and setters (optional, depending on how it affects mutability concerns).

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
