### ISSUE TITLE
[Task] Add deep clone function in Wasm bindings

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#673]
## Description
Expose a `clone` function on most Wasm bindings structs.

## Motivation
The current method of cloning objects we expose in the Wasm bindings is by using `toJSON` to serialize them, then `fromJSON` to deserialize a copy of the object.

We should instead expose a `clone` method on exported structs (that support cloning in Rust) to perform this operation. The benefits are clarity and avoiding overhead of (de)serialization to and from JSON. This will also enable cloning objects that are cloneable in Rust but not (de)serializable.

Note that `fromJSON` should still be retained as developers may use it to deserialize objects serialized with `toJSON` and stored or sent over the wire.

## To-do list

- [ ] Add `clone`.
- [ ] Update Wasm examples.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
