### ISSUE TITLE
[Task] Simple Duration API 

### ISSUE THREAD

**Issue by olivereanderson** [iotaledger/identity.rs#683]
## Description
Port some of the `Duration` functionality from the `time` crate in order to conveniently increment and decrement timestamps. 
 
## Motivation
This will be useful when we introduce the new VC & VP validation API (See issue #631 and PR #599) as that allows the verifier to conveniently express earliest and latest allowed expiration and issuance dates respectively.

More precisely without this functionality a caller would need to do something like this 
```
// Do not allow credentials that expire within the next 10 hours
  let credential_validation_options: CredentialValidationOptions = CredentialValidationOptions::default()
    .earliest_expiry_date(Timestamp::from_unix(Timestamp::now_utc().to_unix() + 10 * 60 * 60)?);
```
while it ideally should be as simple as this:

```
  let credential_validation_options: CredentialValidationOptions = CredentialValidationOptions::default()
    .earliest_expiry_date(Timestamp::now_utc().try_add(Duration::hours(10))?);
```

## To-do list
Create a task-specific to-do list . 

- [ ] Implement a struct `Duration` that wraps `time::Duration` without exposing the `time` dependency. 
- [ ] Implement methods on `Timestamp` to increment it and decrement it with the given duration (make sure that RFC3339 compatibility is preserved). 
- [ ] Expose the functionality from items 1 & 2 to the wasm bindings. 

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
