### ISSUE TITLE
[Task] Replace Wasm Client Config with a Typescript interface

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#685]
## Description
Investigate whether the `Config` class in the Wasm bindings for instantiating `Clients` can be replaced for a Typescript interface for consistency with the rest of the bindings where constructors use duck-typed interfaces instead of builders.

## Motivation
The current `Config` class in the Wasm bindings is analogous to the `ClientBuilder` except it does not expose options that take lists as parameters and it does not follow a builder pattern.

E.g. current usage:
```ts
const config = new Config();
config.setNetwork(Network.mainnet());
config.setEncoding(DIDMessageEncoding.JsonBrotli);
config.setPrimaryNode("http://127.0.0.1:14265/");
const client = await Client.fromConfig(config);
```
compared to the `ClientBuilder`

```rust
let client: Client = ClientBuilder::new()
  .network(Network::Mainnet)
  .encoding(DIDMessageEncoding::JsonBrotli)
  .primary_node("http://127.0.0.1:14265/", None, None)?
  .build()
  .await?;
```

Ideally, an `IClientConfig` interface would be more ergonomic for Typescript, if possible:

```ts
const client = await Client.fromConfig({
  network: Network.mainnet(),
  encoding: DIDMessageEncoding.JsonBrotli,
  primaryNode: "http://127.0.0.1:14265/"
});
```

## To-do list

- [x] Investigate whether a Typescript interface is feasible for all `Config`/`ClientBuilder` options, implement if so.
- [ ] Rename `Config` to `ClientConfig` for clarity if not possible.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
