### ISSUE TITLE
[Task] Combine `resolve_method` functions

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#686]
## Description
Replace the six `*resolve_method*` functions in `IotaDocument`, `CoreDocument` and `WasmDocument` with two functions which return `Option` instead of `Result`.

## Motivation
There are currently six very similar functions on `CoreDocument` (with a subset re-exported from `IotaDocument`) for retrieving verification methods (pseudocode):

- `resolve_method(query) -> Option<&method>`
- `resolve_method_mut(query) -> Option<&mut method>`
- `try_resolve_method(query) -> Result<&method>`
- `try_resolve_method_mut(query) -> Result<&mut method>`
- `resolve_method_with_scope(query, scope) -> Option<&method>`
- `try_resolve_method_with_scope(query, scope) -> Result<&method>`

This seems unnecessary and contributes to API bloat/pollution. The pattern of having separate `try_*` functions is more for when the non-try functions panic on errors, which does not apply here. 

We should rather have only two functions which return `Option`. This moves the responsibility of handling missing methods to the caller and avoids the problem of bubbling up errors without context, which is in accordance with the new error handling guidelines.

Proposed functions (pseudocode):

- `resolve_method(query, Option<scope>) -> Option<&method>`
- `resolve_method_mut(query, Option<scope>) -> Option<&mut method>`

These are sufficient for resolving methods with/without scope and mutably/immutably. This may require far-reaching changes to error handling across the codebase, particularly in places like the `Account` where the returned option will need to be mapped to a new/different error variant.

## To-do list

- [ ] Replace the six `resolve_*` functions on `CoreDocument` and `IotaDocument` with the proposed functions.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
