### ISSUE TITLE
[Task] Encourage best practices in examples 

### ISSUE THREAD

**Issue by olivereanderson** [iotaledger/identity.rs#695]
## Description
The examples in both Rust and JS should not just illustrate the features of the library, but also document best practices. 

## Motivation
This is useful for anyone who wants to learn how to use the library properly. 

## To-do list

- [ ] Use `Presentations` instead of `Credentials` when demonstrating the use of Merkle keys. 
- [ ] Use a dedicated signing method when signing credentials/presentations (See [this comment by @PhilippGackstatter](https://github.com/iotaledger/identity.rs/pull/599#discussion_r819444824)). 
- [ ] Adapt the Rust examples to use `anyhow`/`eyre` to encourage error source reports. This item needs to wait until we consistently avoid including an error source's message in the top level message throughout the code base (See issue #534). 
- [ ] Use `try/catch` in the Wasm/JS examples to illustrate when errors can be thrown and (ideally) how one might handle them. 
- [ ] Consider bringing in a json schema validation library and use it to illustrate what presentation validation might look like at the application level. 

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
