### ISSUE TITLE
[Task] Deprecate diff chain updates

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#703]
## Description
Mark all public functions that work with diff chain resolutions, merges or updates as deprecated. This includes the top-level APIs such as the `Account`, `Client`, and `Resolver` as well as any exposed functions for creating or merging diffs.

We should also always publish full integration chain updates in the `Account` to prevent anyone from performing diff updates that may not be forwards compatible.

## Motivation
The diff chain is at-risk and will likely be removed due to possible technical infeasibility going forward.

## To-do list

- [ ] Mark diff chain functions as deprecated.
  - [ ] Rust
  - [ ] Wasm
- [ ] Change `Account` to always perform integration chain updates.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
