### ISSUE TITLE
[Task] Remove `publicKeyJwk`

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#713]
## Description
Remove `MethodData::publicKeyJwk`.

## Motivation
The `publicKeyJwk` variant in `MethodData` is intended to represent public keys in verification methods encoded as a JWK: https://www.w3.org/TR/did-core/#dfn-publickeyjwk

Right now we represent it as a simple `Object = BTreeMap<String, serde_json::Value>`. 

```rust
pub enum MethodData {
  PublicKeyMultibase(String),
  PublicKeyBase58(String),
  PublicKeyJwk(Object),
}
```

However, it is unused and unsupported elsewhere in the library. 

```rust
pub fn try_decode(&self) -> Result<Vec<u8>> {
  match self {
    Self::PublicKeyMultibase(input) => decode_multibase(input).map_err(|_| Error::InvalidKeyDataMultibase),
    Self::PublicKeyBase58(input) => decode_b58(input).map_err(|_| Error::InvalidKeyDataBase58),
    Self::PublicKeyJwk(_) => Err(Error::InvalidKeyData),
  }
}
```

The problem with keeping `publicKeyJwk` as it stands is that any constraints we place on the representation in the future if/when we do provide full support for JWK representation will not be backwards compatible and break any DID Document that use `publicKeyJwk` incorrectly. E.g. adding unsupported fields, or omitting the `kty` field might cause a deserialization error somewhere in the DID Document chain in the past, breaking it and losing all subsequent updates. Such a case would be a security risk if old verification methods were rotated due to their private keys being leaked.

Even if an application might be using it as a representation outside of this library currently, which is unlikely, the risk of a backwards-incompatible breaking change to DID Documents by keeping `publicKeyJwk` is not worth it.

## Resources
- https://www.w3.org/TR/did-core/#dfn-publickeyjwk

## To-do list

- [ ] Remove `MethodData::publicKeyJwk`

## Change checklist

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
