### ISSUE TITLE
[Task] Move `proof` in `IotaDocument` outside of metadata

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#714]
## Description
Move the `proof` section in `IotaDocument` from inside its `metadata` to the root level. 

Current JSON:
```json
"doc": {},
"meta": { 
  "proof": {},
  ... 
}
```

Proposed JSON:
```json
"doc": {},
"meta": {},
"proof": {}
```

## Motivation
This change would remove the special case for signing DID Documents, which stands in contrast to all other structs which have their proof at the root level, such as `Credential` and `Presentation`.

While in Rust this is handled by the `SetSignature` trait, this discrepancy has caused problems in the Wasm bindings and will likely continue to cause problems. This also causes problems when verifying data, because we need to know what type of data we're dealing with in order to know where its signature is located.

The simplest solution is to move the DID Document `proof` to align with other objects.

## To-do list

- [ ] Move `proof` in `IotaDocument`.
- [ ] Update the IOTA DID Method Specification.

## Change checklist

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by eike-hass** [comment]
We need to verify this change against the explorer application. It expects only the the `doc` and `meta` root keys. I assume ATM you would not be able to inspect the proof in the UI with this change.

**Comment by cycraig** [comment]
I believe the `proof` field was manually removed from the JSON in the initial release of the explorer, if I'm not mistaken. Was it added back in the refactor for 0.5? Needs investigating either way, thanks for the heads-up.
