### ISSUE TITLE
[Task] Remove `MerkleKeyCollection2021`

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#715]
## Description
Remove `MerkleKeyCollection2021` and all associated structs.

## Motivation
The primary purpose of `MerkleKeyCollection2021` is to provide a means to issue and revoke verifiable credentials individually. Unfortunately, there are problems with it scaling due to having to store each individual private key in the collection in the current implementation. So to issue one million individually-revocable credentials, I need to store one million keys.

The intended use-case of revoking each credential individually means using each constituent key only once, and there are existing one-time-signature schemes that do not require storing each key but rather a single root key and associated state. Storing used private keys without being able to use them without losing the capability for individual revocation is unnecessary.

There are also [`credentialStatus`](https://www.w3.org/TR/vc-data-model/#status) specifications that enable revoking credentials individually, separate from the verification method and signature used, such as [Revocation List 2020](https://w3c-ccg.github.io/vc-status-rl-2020/). While one could argue that `MerkleKeyCollection2021` is useful for potentially revoking arbitrary signatures/messages, one can still achieve that by incorporating a scheme similar to `credentialStatus` for arbitrary signed data at scale. In general, `credentialStatus` is more flexible since it is not necessarily tied to a DID Document (which could be seen as a disadvantage in some situations but one can always create a status scheme that _is_ tied to a DID Document) and allows separating revocation from the signature, since it is useful to know whether a signed message was _ever_ valid or simply revoked later.

The argument could be made that the keys could be distributed to allow a compact verification method able to be used by multiple parties, but there also exist "k of n" multi-sig schemes that could be used equivalently in a "1 of n" setting.

Overall, while incredibly useful and acknowledging that improvements to it could be made, `MerkleKeyCollection2021` will eventually be replaced by one or more alternatives. To avoid a backwards-incompatible breaking change to DID Documents in the future, we should remove it completely now, even without an alternative in place. We could decide to add it back later in an improved and stable form with indefinite support.

## Resources
- https://wiki.iota.org/identity.rs/specs/did/merkle_key_collection
- https://www.w3.org/TR/vc-data-model/#status
- https://w3c-ccg.github.io/vc-status-rl-2020/

## To-do list

- [ ] Remove `MerkleKeyCollection2021` and all associated structs.
- [ ] Update the documentation, IOTA DID Method Specification.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
