### ISSUE TITLE
[Task] Remove `Storage::set_password`

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#720]
## Description
Remove the `set_password()` function from the account `Storage` interface.

## Motivation
Password management is specific to Stronghold right now and should be handled by the Stronghold wrapper or its library rather than requiring that all `Storage` implementers deal with it.

## Resources
This is a sub-task extracted from:
- https://github.com/iotaledger/identity.rs/issues/669

## To-do list

- [ ] Remove `Storage::set_password`

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
