### ISSUE TITLE
[Task] Change keys in Wasm from Base58-BTC strings to `UInt8Array`

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#721]
## Description
Change the public, private key representations used in the Wasm bindings from Base58-BTC encoded `String`s to `UInt8Array`.

## Motivation
Keys are not generally meant to be viewable and developers can encode them however they wish. `UInt8Array` is also the format expected by existing libraries such as `TweetNaCl`, so from an interoperability standpoint using `UInt8Array` would be more convenient.

May cause issues with the Stronghold Napi bindings though.

## Resources
This is a sub-task extracted from:
- https://github.com/iotaledger/identity.rs/issues/669

## To-do list

- [ ] Change keys in Wasm from Base58-BTC strings to `UInt8Array`

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by HenriqueNogara** [comment]
#734
