### ISSUE TITLE
[Task] Refactor `Account` `Signature`

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#722]
## Description
Refactor the `Account` `Signature` struct to either an enum, or the raw bytes of the signature, or simply `Vec<u8>`/`UInt8Array`.

## Motivation
The `public_key` field in `Signature` is unused. Currently supported signing methods (`Ed25519`, `MerkleKeyCollection`) only require a single byte array to be embedded in the `proof` for the signature so we can just return that alone.

Note that future signature schemes may require extra information to be returned, so an enum might be more prudent to avoid breaking changes in the future, optionally.

Note that `UInt8Array` may cause problems with the Napi Stronghold bindings.

## Resources
This is a sub-task extracted from:
- https://github.com/iotaledger/identity.rs/issues/669

## To-do list

- [ ] Decide whether Signature should be a type alias for `Vec<u8>` or a newtype wrapper, and consider the effects on bindings in that decision.
- [ ] Replace `Account` `Signature` with a byte array or enum as appropriate.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
