### ISSUE TITLE
[Task] Add Diffie-Hellman key exchange to `Account`

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#756]
## Description
Add support for Diffie-Hellman key exchange operations in `Account`.

## Motivation
Adding support for `X25519` keys included using them to perform Diffie-Hellman key exchange. We should expose this functionality through the `Account` too, since `Storage` prevents direct access to the private keys required to perform it. I.e. developers have no alternative if we do not support this feature directly.

The current function (not using the `Account`) looks as follows:
```rust
/// Performs a cryptographic key exchange process (e.g. Diffie-Hellman) using the private key
/// of the first party with the public key of the second party, resulting in a shared secret.
pub fn key_exchange<PRV, PUB>(private: &PRV, public: &PUB) -> Result<[u8; 32]>
where
  PRV: AsRef<[u8]> + ?Sized,
  PUB: AsRef<[u8]> + ?Sized,
{
  let private_key: x25519::SecretKey = x25519::SecretKey::try_from_slice(private.as_ref())?;
  let public_key: x25519::PublicKey = x25519::PublicKey::try_from_slice(public.as_ref())?;
  Ok(private_key.diffie_hellman(&public_key).to_bytes())
}
```

## Resources
- https://github.com/iotaledger/identity.rs/issues/671
- https://github.com/iotaledger/identity.rs/pull/735
- https://datatracker.ietf.org/doc/html/rfc7748#section-6.1
- https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange

## To-do list

- [ ] Add Diffie-Hellman key exchange function to `Account`/`Storage`.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
