### ISSUE TITLE
[Task] Upgrade to new Stronghold interface

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#785]
## Description

Upgrade Stronghold to the new client interface.

## Motivation

The new interface allows us to get rid of our password management solution and a big chunk or even all of our custom stronghold wrapper.

## To-do list
Create a task-specific to-do list. Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Use stronghold's native password management.
- [ ] Use the new client interface.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
