### ISSUE TITLE
[Task] Fix musl target for the Stronghold Napi bindings

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#786]
## Description
Fix Stronghold Napi binding builds for the musl target and re-add the target to the build and publish steps in the CI/CD workflows.

## Motivation
Stronghold Napi builds for the `x86_64-unknown-linux-musl` target were broken by an undetermined change in PR #729. The error appears to be related to failure to load a DLL, or a specific glibc function: `__register_atfork: symbol not found`.

Error log:
```js
exit status: 1
  stderr: |
    /build/bindings/stronghold-nodejs/dist/index.js:300
        throw loadError
        ^

    Error: Error relocating /build/bindings/stronghold-nodejs/dist/identity-stronghold-nodejs.linux-x64-musl.node: __register_atfork: symbol not found
        at Object.Module._extensions..node (node:internal/modules/cjs/loader:1185:18)
        at Module.load (node:internal/modules/cjs/loader:[98](https://github.com/iotaledger/identity.rs/runs/5772708860?check_suite_focus=true#step:12:98)1:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.require (node:internal/modules/cjs/loader:[100](https://github.com/iotaledger/identity.rs/runs/5772708860?check_suite_focus=true#step:12:100)5:19)
        at require (node:internal/modules/cjs/helpers:[102](https://github.com/iotaledger/identity.rs/runs/5772708860?check_suite_focus=true#step:12:102):18)
        at Object.<anonymous> (/build/bindings/stronghold-nodejs/dist/index.js:225:31)
        at Module._compile (node:internal/modules/cjs/loader:1[103](https://github.com/iotaledger/identity.rs/runs/5772708860?check_suite_focus=true#step:12:103):14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
      code: 'ERR_DLOPEN_FAILED'
    }
```

The decision was made to remove the musl target from CI/CD and not publish it to avoid delaying the release of version 0.5.0.

The musl target is important as it allows Stronghold Napi to be used in lightweight containers running on musl-based distributions such as Alpine/Busybox and therefore should be restored if possible.

## To-do list

- [ ] Fix Stronghold Napi bindings for `x86_64-unknown-linux-musl`
- [ ] Restore the musl triple in `bindings/stronghold-nodejs/package.json`
- [ ] Restore the musl target in `.github/workflows/shared-build-and-test-stronghold-nodejs.yml`

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
