### ISSUE TITLE
[Task] Implement a `Storage` test suite

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#790]
## Description

Implement a test suite for the `Storage` interface.

## Motivation

With multiple internal implementations of our `Storage` interface, as well as the ability for users of our framework to implement their own storage, it makes sense to provide a generic test suite that tests the interface's implementation.

## To-do list
Create a task-specific to-do list. Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Implement tests for the `Storage` test suite.
- [ ] Expose the tests in Rust and bindings.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
