### ISSUE TITLE
[Task] Add `Client` option for retry publishing behaviour

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#811]
## Description
Add a `retry_until_included` option (or whatever name is decided) to the `ClientBuilder`.

## Motivation
Currently when publishing DID Documents or updates the `Client` waits and retries until the message is confirmed by a milestone. This behaviour should be configurable.

## Resources
- PR which added the current publishing behaviour: #455

## To-do list

- [ ] Add `ClientBuilder::retry_until_included`.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
