### ISSUE TITLE
[Task] Improve Credential, Presentation creation in Wasm

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#813]
## Description
Use duck-typed interfaces and port relevant structs to the Wasm bindings to make constructing verifiable credentials and presentations more type-safe and ergonomic.

## Motivation
Currently, constructing a `Credential` in the Wasm bindings is done through pure JSON and does not follow the duck-typed constructor pattern used throughout the bindings:

E.g.
```ts
// Create a credential subject indicating the degree earned by Alice.
const credentialSubject = {
    id: alice.document().id().toString(),
    name: "Alice",
    degreeName: "Bachelor of Science and Arts",
    degreeType: "BachelorDegree",
    GPA: "4.0"
};

// Create an unsigned `UniversityDegree` credential for Alice
const unsignedVc = Credential.extend({
    id: "https://example.edu/credentials/3732",
    type: "UniversityDegreeCredential",
    issuer: issuer.document().id().toString(),
    credentialSubject,
});
```

where `extend` is one of the last places where the undesirable `any` type is used:

```ts
static extend(value: any): Credential;
```

Similarly, constructing a `Presentation` takes `any` and lacks the options for other fields available in Rust such as setting the types, context, refresh service or policies:

```ts
// Deserialize the credential.
const receivedVc = Credential.fromJSON(signedVcJson);

// Create a Verifiable Presentation from the Credential
const unsignedVp = new Presentation(alice.document(), receivedVc)
```

where the constructor again takes `any`:

```ts
  constructor(holder_doc: Document, credential_data: any, presentation_type?: string, presentation_id?: string);
```

### Proposed Syntax

The proposal is to replace the above with duck-typed interfaces for the constructors of `Credential` and `Presentation`. These interfaces would use exported types for things like refresh services and policies but it's unclear how to work with `credentialSubject` as that is entirely user-defined. We could create an interface which defines the minimum fields required (basically just an optional `id` URI), or leave it as `any`.

E.g.

```ts
/** Fields for creating a new `Credential`. */
interface ICredential {
  /** The JSON-LD context(s) applicable to the `Credential`. */
  readonly context?: string | Record<string, any> | Array<string | Record<string, any>>;

  /** A unique `URI` referencing the subject of the `Credential`. */
  readonly id?: string;
 
  /** One or more URIs defining the type of the `Credential`. */
  readonly type?: string | Array<string>;

  /** One or more objects representing the `Credential` subject(s). */
  readonly credentialSubject: TODO ISubject | Array<ISubject> ?;

  /** A reference to the issuer of the `Credential`. */
  readonly issuer: string | IIssuer;
  
  /** A timestamp of when the `Credential` becomes valid. Defaults to the current datetime. */
  readonly issuanceDate?: Timestamp; 

  /** A timestamp of when the `Credential` should no longer be considered valid. */
  readonly expirationDate?: Timestamp; 

  /** Information used to determine the current status of the `Credential`. */
  readonly credentialStatus?: Status | Array<Status>;

  /** Information used to assist in the enforcement of a specific `Credential` structure. */
  readonly credentialSchema?: Schema | Array<Schema>;

  /** Service(s) used to refresh an expired `Credential`. */
  readonly refreshService?: RefreshService | Array<RefreshService>;

  /** Terms-of-use specified by the `Credential` issuer. */
  readonly termsOfUse?: Policy | Array<Policy>;

  /** Human-readable evidence used to support the claims within the `Credential`. */
  readonly evidence?: Evidence | Array<Evidence>;

  /** Indicates that the `Credential` must only be contained within a {@link Presentation} with a proof issued from the `Credential` subject. */
  readonly nonTransferable?: boolean;

  /** Miscellaneous properties */
  readonly properties?: Record<string | any>;
}
```

## Resources
- Verifiable Credentials Data Model specification: https://www.w3.org/TR/vc-data-model

## To-do list

- [ ] Add a duck-typed constructor for `Credential`.
- [ ] Add a duck-typed constructor for `Presentation`.
- [ ] Update examples.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
