### ISSUE TITLE
[Doc] Populate or remove empty wiki pages

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#821]
## Description
There are several pages on the Identity wiki that have no content other than a TODO. We need to decide to write content for these pages or remove them entirely.

## To-do List

Separate PRs are welcome for the following.

- [ ] Remove empty DID Communications pages: https://wiki.iota.org/identity.rs/did_communications/overview
- [ ] Remove Signature Schemes page: https://wiki.iota.org/identity.rs/advanced/signature_schemes
- [ ] Remove IOTA Client page: https://wiki.iota.org/identity.rs/advanced/client
- [ ] Remove Rust Troubleshooting?: https://wiki.iota.org/identity.rs/libraries/rust/troubleshooting
- [ ] Remove Wasm Troubleshooting?: https://wiki.iota.org/identity.rs/libraries/wasm/troubleshooting
- [ ] Populate Contact page: https://wiki.iota.org/identity.rs/contact
  - Maybe just move the link to the public Discord channel from Contribute to Contact?
- [ ] Populate FAQ page: https://wiki.iota.org/identity.rs/faq
