### ISSUE TITLE
[Task] Update the resolution examples to use the new Resolver 

### ISSUE THREAD

**Issue by olivereanderson** [iotaledger/identity.rs#835]
## Description
Update the Resolution examples `examples/low_level/resolution` and `examples/low_level/resolve_history` to use the new `Resolver` instead of the now deprecated spec compliant resolution API. 

## Motivation
The examples should not encourage using deprecated methods and this particular case the update was requested by @JelleMillenaar  in his review of #823. 

## Resources
#823 is blocked by this task. 

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Update the examples for the Rust library
- [ ] Update the examples for the Wasm library

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by olivereanderson** [comment]
Closed by https://github.com/iotaledger/identity.rs/pull/838
