### ISSUE TITLE
[Task] Avoid cross compilation when building the musl `stronghold-nodejs` binary

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#837]
## Description

Change our build process of the musl stronghold-nodejs binary so it is no longer cross-compiled. Instead we want to build in a musl container directly that avoid cross-compilation.

## Motivation

The current build process is prone to failure whenever `rand::thread_rng()` or `rand::random()` is called. See #786 for more details. The problem resurfaced in #787.

## Resources

#786 
#789

## To-do list
Create a task-specific to-do list. Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Change build process to run in a musl container.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
