### ISSUE TITLE
[Task] Implement a minimal JOSE library

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#841]
## Description

Implement a minimal JOSE library based on work done in `libjose`.

To keep the scope of this issue reasonable, the library only needs to facilitate anonymous encryption as part of the IOTA DIDComm protocol. Of course, this library should eventually be extendable to support other DIDComm cryptography like signing and sender-authenticated encryption.

## Motivation

While `libjose` is full-featured, it supports many more features than we need and are comfortable to maintain. Most importantly, it is not designed to support calling out to `Storage` from asynchronous contexts.

## Resources

Our libjose library.

## To-do list
Create a task-specific to-do list. Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Implement a library to support creation of JWE messages.
- [ ] Tailor it to the needs of DIDComm, only requiring `ECDH-ES+A256KW` with curve `X25519` as part of this issue.
- [ ] Enable calling a `Storage` instance for de- and encryption.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
