### ISSUE TITLE
[Task] Implement the IOTA DIDComm Connection protocol

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#842]
## Description

Implement the IOTA DIDComm Connection protocol using the actor.

## Motivation

Add DIDComm support for the actor in a specified way.

## Resources

https://wiki.iota.org/identity.rs/specs/didcomm/protocols/connection

## To-do list
Create a task-specific to-do list. Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Implement #841.
- [ ] Implement the IOTA DIDComm protocol in the actor.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by eike-hass** [comment]
We have no plans to add DIDComm support
