### ISSUE TITLE
[Task] Implement DID Deactivation in the `Account`

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#851]
## Description

A proposal for DID Document deactivation:

Add an `Account::deactivate_identity` method, that publishes a deactivated DID document and waits for milestone confirmation (without the user being able to override this, although if there's a reasonable argument why someone would want that, we can also offer the option). This does not delete any local keys or state. Once a user is sure that they want the `Account` to be gone for good, they can call `Account::delete_identity` to purge every key and state associated to the identity. In `delete_identity` we may want to check if a deactivation update was published and throw an error otherwise. Even if a deactivation update fails to be included in the Tangle, another one can be attempted because the key is still in storage. The last key(s) capable to sign a document update will be permanently wiped with `delete_identity` instead.

This essentially separates deactivation and key deletion and puts the user in control of when exactly to purge the identity. 

(mostly copied from [#757](https://github.com/iotaledger/identity.rs/issues/757#issuecomment-1118371223))

## Motivation

The account currently lacks a way to deactivate a DID and delete the corresponding keys in `Storage`.

## Resources

The discussion about key deletion is at least related #757.

## To-do list
Create a task-specific to-do list. Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Implemented the `deactivate_identity` method as described.
- [ ] Implement `delete_identity` as described.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
