### ISSUE TITLE
[Task] Take control of iota-identity-tutorial repository

### ISSUE THREAD

**Issue by eike-hass** [iotaledger/identity.rs#907]
## Description
We should take control of https://github.com/adrian-grassl/iota-identity-tutorial/ and update the repository and the wiki pages.

## Motivation
Provide up to date tutorials for implementors.

## Resources
Original repository: https://github.com/adrian-grassl/iota-identity-tutorial/

## To-do list

- [X] Figure out transfer process and license, or consider moving the files into our repository.
- [ ] Update repository content.
- [ ] Update wiki content.
- [ ] Use `Account` instead of low-level API, and thus also `Stronghold` instead of the `Weakhold`.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
