### ISSUE TITLE
[Task] Implement StardustDID 

### ISSUE THREAD

**Issue by olivereanderson** [iotaledger/identity.rs#945]
## Description
Implement the equivalent of the `IotaDID`, `CoreDID` types for Stardust. 

## Resources
Sub-task of https://github.com/iotaledger/identity.rs/issues/908. 

## To-do list
Create a task-specific to-do list. Please link PRs that match the TODO list item behind the item after it has been submitted.

- [ ] Make type convert to and from Strings of the form `did:stardust:<network>:<tag=AliasID>` 
- [ ] Make type compatible with the initial `AliasID := 0x000000000.....`. Determine if there needs to be one "independent copy" of this ID per supported network.  

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
