### ISSUE TITLE
[Task] Implement Client for Stardust

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#950]
## Description

Implement an interface or wrapper for iota.rs.

Given the increased complexity of the client with the stardust, it might make more sense to implement an interface rather than wrap and re-expose many of its options. We also have to consider Wasm compatibility, either through compilation of iota.rs to Wasm or by binding iota.js.

## Motivation

Ease publishing and resolving of DID Documents in alias outputs.

## Resources

part of #908

## To-do list
Create a task-specific to-do list. Please link PRs that match the TODO list item behind the item after it has been submitted.

- [ ] Decide on the approach for interface or wrapper.
- [ ] Implement interface/wrapper.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
