### ISSUE TITLE
[Task] Incorporate `Network` and `NetworkName` into the `StardustDID` API. 

### ISSUE THREAD

**Issue by olivereanderson** [iotaledger/identity.rs#954]
## Description
Once types representing networks compliant with the Stardust UTXO-based DID method exist they should be used in the `StardustDID` API. See the "To-do list" section for more precise details about what needs to be done in this regard.  

## Resources
Sub-task of #908.  

## To-do list
Create a task-specific to-do list. Please link PRs that match the TODO list item behind the item after it has been submitted.

- [ ] Change the type of the constant `StardustDID::DEFAULT_NETWORK` to be of type `NetworkName`.  
- [ ] Implement features gated constructor `StardustDID::from_alias_id(alias_id : AliasId, Option<Network>) -> Self`. The method should be feature gated in order to avoid a hard (default) dependency on `iota_client`. 
- [ ] Implement a ["builder lite"](https://matklad.github.io/2022/05/29/builder-lite.html) method `StardustDID::with_network(self, network: `Network`) -> Self`. Perhaps one should take `NetworkName` here instead or there should be two methods to support both alternatives? 
- [ ]  Implement a constructor `placeholder(network: NetworkName) -> Self`. 
- [ ]  Implement a constructor `new_with_network(bytes: [u8;32], network: NetworkName) -> Self`.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
