### ISSUE TITLE
[Doc] Improve DID Method Specifications

### ISSUE THREAD

**Issue by abdulmth** [iotaledger/identity.rs#974]
## Description
Improve the method specs of the UTXO method.

## To-do List

- [ ] Check if terms are up to date.
- [ ] Add diagrams. For example to explain how UTXO works.
- [ ] Explain how native tokens can be used with DID (debatable).
- [ ] Abstract away the stardust details in the CRUD operations.

**Comment by cycraig** [comment]
Is this issue completed?

**Comment by abdulmth** [comment]
@cycraig not really, none of the points has been done yet, especially abstracting the stardust details, which is also a debatable point.
