### ISSUE TITLE
[Task] Display controller, state controller, governor addresses

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#983]
## Description
Include the state controller and governor addresses in the DID Document of resolved DIDs or their metadata, and set the `controller` field accordingly.

## Motivation
Alias Outputs are ultimately controlled according to the state controller and governor unlock conditions. It would be convenient to display this information on resolved DID Documents.

Additionally, the controller field should reflect the DID of the state controller if it is an `AliasId`/`AliasAddress`. We cannot tell prior to resolution whether an Alias Output actually contains a DID Document, but treating every AliasId as an IOTA DID is probably fine.

## Open Questions

1. Does this pose a security risk? Is there any reason _not_ to include this information? It is public information on the ledger and visible on the Alias Output itself, so we're not displaying any new or privileged information.
2. Should any other properties from the Alias Output be included in resolved DID Documents, e.g. the sender feature address, or immutable issuer feature address?

## To-do list

- [ ] Populate the `controller` field.
- [ ] Decide how and where to display the state controller and governor addresses.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
