### ISSUE TITLE
[Task] Port Rust Stardust examples to Wasm

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#984]
## Description

Port the Rust examples introduced in #981 to Wasm, ideally also using Stronghold.

## Motivation

Parity between Rust and Wasm.

## Resources

#981

## To-do list
Create a task-specific to-do list. Please link PRs that match the TODO list item behind the item after it has been submitted.

- [ ] Port the Rust examples to Wasm.
- [ ] Rename to `<digit>_example_name`.

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.
