### ISSUE TITLE
[Task] Change default network name from `main` to `iota`

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#985]
## Description
Change the default network name for Stardust from `main` to `iota`.

## Motivation
We're going with the Bech32 Human-Readable Part (HRP) for the network names, so the default network should change to `iota`.

I.e.
`did:iota:iota:0x12345...` should canonicalise to 
`did:iota:0x12345...`

## To-do list

- [ ] Change default Stardust network name from `main` to `iota` .
- [ ] Update doc-comments and documentation.
- [ ] Update Wasm bindings

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by PhilippGackstatter** [comment]
Fixed in #1000.
